/**
 * Synthetic-agent builders for simulator scaffolding tests.
 *
 * These exist so the simulator can be exercised end-to-end without any
 * real CES/ANES data. Once the survey-mapping track delivers a real
 * mapper, this module is no longer the source of truth — it stays as
 * a fixture for unit tests + the scaffold smoke.
 *
 * agentFromArchetype:
 *   Wraps a single archetype as a WeightedAgent with N posterior samples
 *   generated by jittering the centroid. Each archetype becomes one agent.
 *
 * agentsFromArchetypes:
 *   Convenience: build one agent per archetype, all sharing the same year.
 *
 * Use these in smoke / scaffold tests, not in production paths.
 */

import { ARCHETYPES } from "../config/archetypes.js";
import type { Archetype, MorBoundariesNodeState } from "../types.js";
import type { NodeSignature } from "../engine/respondentSignature.js";
import type { EngagementLevel } from "../engine/engagementLabel.js";
import type { WeightedAgent } from "./types.js";

const DEACTIVATED_ARCHETYPE_IDS = new Set(["019", "023", "025"]);

const CONTINUOUS_SCORING_NODES = [
  "MAT", "CD", "CU", "MOR", "PRO", "COM", "ZS", "ONT_H", "ONT_S", "PF", "TRB",
] as const;
const CATEGORICAL_NODES = ["EPS", "AES"] as const;

function clamp(x: number, lo: number, hi: number): number {
  return Math.max(lo, Math.min(hi, x));
}

function engagementLevelFromPos(pos: number): EngagementLevel {
  if (pos < 2.0) return "apolitical";
  if (pos < 3.0) return "casual";
  if (pos < 4.0) return "engaged";
  return "highly-engaged";
}

/** Centroid signature for an archetype — used as the base before jitter. */
function archetypeCentroidSignature(arc: Archetype): NodeSignature {
  const sig: NodeSignature = {};
  for (const code of CONTINUOUS_SCORING_NODES) {
    const n = arc.nodes[code];
    if (!n || n.kind !== "continuous") continue;
    sig[code] = { pos: n.pos, sal: n.sal };
  }
  for (const code of CATEGORICAL_NODES) {
    const n = arc.nodes[code];
    if (!n || n.kind !== "categorical") continue;
    let expectedIdx = 0;
    for (let i = 0; i < n.probs.length; i++) expectedIdx += i * n.probs[i];
    sig[code] = { pos: expectedIdx, sal: n.sal, catDist: [...n.probs] };
  }
  return sig;
}

/**
 * Jitter a centroid signature by Gaussian noise on continuous-node pos
 * (sal kept fixed) to produce a posterior sample. Categorical nodes are
 * not jittered (would require renormalizing the catDist; not worth it
 * for v0 scaffolding).
 */
function jitterSignature(centroid: NodeSignature, posSigma: number, rng: () => number): NodeSignature {
  const out: NodeSignature = {};
  for (const [code, entry] of Object.entries(centroid)) {
    if (!entry) continue;
    if (entry.catDist) {
      // Categorical: pass through unchanged for v0.
      out[code as keyof NodeSignature] = { ...entry };
    } else {
      const u1 = rng() || 1e-9;
      const u2 = rng();
      const z = Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2);
      const pos = clamp(entry.pos + z * posSigma, 1, 5);
      out[code as keyof NodeSignature] = { pos, sal: entry.sal };
    }
  }
  return out;
}

/** Deterministic mulberry32 RNG so smoke runs are reproducible. */
export function makeRng(seed: number): () => number {
  let a = seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export interface AgentFromArchetypeOpts {
  electionYear: number;
  weight?: number;
  samples?: number;
  posSigma?: number;
  rng?: () => number;
  partyID?: WeightedAgent["partyID"];
  source?: string;
}

/**
 * Build a single WeightedAgent representing this archetype, with N posterior
 * samples around its centroid. Engagement comes from the archetype's ENG node.
 */
export function agentFromArchetype(
  arc: Archetype,
  opts: AgentFromArchetypeOpts,
): WeightedAgent {
  const { electionYear } = opts;
  const weight = opts.weight ?? 1;
  const samples = opts.samples ?? 1;
  const posSigma = opts.posSigma ?? 0;
  const rng = opts.rng ?? makeRng(parseInt(arc.id, 10) || 42);
  const source = opts.source ?? "SYNTHETIC-ARCHETYPE";

  const centroid = archetypeCentroidSignature(arc);
  const signatureSamples: NodeSignature[] =
    samples <= 1 || posSigma <= 0
      ? [centroid]
      : Array.from({ length: samples }, () => jitterSignature(centroid, posSigma, rng));

  const engNode = arc.nodes.ENG;
  const engPos = engNode && engNode.kind === "continuous" ? engNode.pos : 3;
  const engagement = engagementLevelFromPos(engPos);

  // Find dominant scoring node by salience for predictVote's optional weighting.
  let dominantNode: string | null = null;
  let dominantSal = -1;
  for (const code of CONTINUOUS_SCORING_NODES) {
    const n = arc.nodes[code];
    if (!n || n.kind !== "continuous") continue;
    if (n.sal > dominantSal) { dominantSal = n.sal; dominantNode = code; }
  }

  const morBoundariesState: MorBoundariesNodeState | null = arc.morBoundaries
    ? { boundaries: { ...arc.morBoundaries.boundaries }, intensity: arc.morBoundaries.intensity }
    : null;

  return {
    id: `arc-${arc.id}`,
    electionYear,
    source,
    weight,
    signatureSamples,
    engagement,
    partyID: opts.partyID ?? null,
    dominantNode,
    morBoundariesState,
    demographics: { extra: { archetypeName: arc.name, archetypeId: arc.id } },
  };
}

export interface AgentsFromArchetypesOpts extends Omit<AgentFromArchetypeOpts, "weight"> {
  /** weight per archetype, OR a function returning weight given the archetype. */
  weight?: number | ((arc: Archetype) => number);
  excludeIds?: Set<string>;
}

export function agentsFromArchetypes(opts: AgentsFromArchetypesOpts): WeightedAgent[] {
  const exclude = opts.excludeIds ?? DEACTIVATED_ARCHETYPE_IDS;
  return ARCHETYPES.filter(a => !exclude.has(a.id)).map(arc => {
    const w = typeof opts.weight === "function" ? opts.weight(arc) : (opts.weight ?? 1);
    return agentFromArchetype(arc, { ...opts, weight: w });
  });
}
