export interface RegimePeriod {
  jurisdiction: string;
  regime: string;
  startYear: number;
  endYear: number;
  MAT: number; CD: number; CU: number; MOR: number;
  PRO: number; COM: number; ZS: number;
  ONT_H: number; ONT_S: number;
  PF: number; TRB: number; ENG: number;
  EPS: number; AES: number;
  description: string;
}

export const EUROPE_PART1: RegimePeriod[] = [
  // ===== UNITED KINGDOM =====
  {
    jurisdiction: "United Kingdom",
    regime: "Georgian Britain",
    startYear: 1789,
    endYear: 1819,
    MAT: 5, CD: 4, CU: 2, MOR: 3,
    PRO: 4, COM: 3, ZS: 3,
    ONT_H: 2, ONT_S: 2,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "Tory oligarchy presiding over early industrialization and reacting to the French Revolution with repressive measures like the Six Acts. A landed aristocratic order defending property and tradition against radical agitation."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "Reform Era",
    startYear: 1820,
    endYear: 1848,
    MAT: 4, CD: 4, CU: 3, MOR: 3,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "The Great Reform Act of 1832 expanded the franchise modestly, while Chartism pushed for deeper democracy. Repeal of the Corn Laws in 1846 marked the triumph of free-trade liberalism over landed protectionism."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "Victorian Peak",
    startYear: 1849,
    endYear: 1874,
    MAT: 5, CD: 4, CU: 3, MOR: 3,
    PRO: 4, COM: 4, ZS: 2,
    ONT_H: 4, ONT_S: 1,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 0, AES: 0,
    description: "The zenith of British imperial and industrial confidence under Gladstone and Disraeli, characterized by laissez-faire economics and positive-sum optimism. Britain saw itself as the workshop of the world with a stable constitutional order."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "Late Victorian/Edwardian",
    startYear: 1875,
    endYear: 1913,
    MAT: 4, CD: 4, CU: 3, MOR: 3,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 3, ONT_S: 2,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 0, AES: 0,
    description: "New Liberalism introduced social reform with Lloyd George's People's Budget while imperial competition intensified with Germany. The Labour movement emerged as a political force alongside growing demands for Irish Home Rule and women's suffrage."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "WWI & Lloyd George",
    startYear: 1914,
    endYear: 1922,
    MAT: 3, CD: 4, CU: 3, MOR: 3,
    PRO: 3, COM: 3, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 4, TRB: 4, ENG: 5,
    EPS: 1, AES: 4,
    description: "Total war mobilized British society on an unprecedented scale, shattering Victorian certainties. Irish independence, suffrage expansion, and the decline of the Liberal Party reshaped the political landscape."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "Interwar",
    startYear: 1923,
    endYear: 1938,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 2, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "The Baldwin-MacDonald era saw cautious conservatism, the General Strike of 1926, and the policy of appeasement toward fascist powers. Mass unemployment and the Jarrow March highlighted deep economic inequality."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "WWII Britain",
    startYear: 1939,
    endYear: 1945,
    MAT: 2, CD: 4, CU: 2, MOR: 4,
    PRO: 2, COM: 2, ZS: 5,
    ONT_H: 3, ONT_S: 5,
    PF: 3, TRB: 5, ENG: 5,
    EPS: 0, AES: 4,
    description: "Churchill's wartime leadership united the nation in total mobilization against Nazi Germany. The Beveridge Report laid the intellectual foundations for the post-war welfare state amid a sense that the old order could not return."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "Attlee/Consensus",
    startYear: 1946,
    endYear: 1964,
    MAT: 2, CD: 3, CU: 3, MOR: 4,
    PRO: 4, COM: 4, ZS: 2,
    ONT_H: 4, ONT_S: 3,
    PF: 4, TRB: 2, ENG: 4,
    EPS: 0, AES: 0,
    description: "The Attlee government created the NHS, nationalized key industries, and built the welfare state. Both parties broadly accepted the post-war settlement of mixed economy and decolonization through the Butskellite consensus."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "Wilson/Heath",
    startYear: 1965,
    endYear: 1978,
    MAT: 2, CD: 2, CU: 4, MOR: 4,
    PRO: 3, COM: 4, ZS: 3,
    ONT_H: 4, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 0,
    description: "The permissive society liberalized social norms while Britain joined the EEC and faced mounting union militancy. The Winter of Discontent and stagflation signaled the exhaustion of the post-war consensus."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "Thatcher Era",
    startYear: 1979,
    endYear: 1990,
    MAT: 5, CD: 4, CU: 3, MOR: 3,
    PRO: 4, COM: 1, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 5, TRB: 4, ENG: 5,
    EPS: 0, AES: 4,
    description: "Thatcher's monetarist revolution privatized state industries, broke union power, and reasserted British sovereignty in the Falklands. Her uncompromising style polarized the country but fundamentally reshaped its political economy."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "New Labour/Blair",
    startYear: 1991,
    endYear: 2009,
    MAT: 3, CD: 2, CU: 4, MOR: 4,
    PRO: 4, COM: 5, ZS: 2,
    ONT_H: 4, ONT_S: 2,
    PF: 4, TRB: 2, ENG: 3,
    EPS: 0, AES: 0,
    description: "Blair's Third Way blended market economics with social investment, devolved power to Scotland and Wales, and pursued liberal interventionism abroad including the Iraq War. A period of relative optimism and consensus-seeking."
  },
  {
    jurisdiction: "United Kingdom",
    regime: "Austerity/Brexit",
    startYear: 2010,
    endYear: 2026,
    MAT: 4, CD: 4, CU: 3, MOR: 3,
    PRO: 3, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 5, TRB: 4, ENG: 5,
    EPS: 3, AES: 4,
    description: "Austerity economics under the Coalition gave way to the Brexit earthquake, fracturing both major parties along cultural lines. Culture wars, populist rhetoric, and institutional distrust defined an era of political volatility."
  },

  // ===== FRANCE =====
  {
    jurisdiction: "France",
    regime: "Ancien Regime remnant",
    startYear: 1789,
    endYear: 1791,
    MAT: 4, CD: 5, CU: 1, MOR: 2,
    PRO: 2, COM: 3, ZS: 4,
    ONT_H: 2, ONT_S: 5,
    PF: 2, TRB: 4, ENG: 5,
    EPS: 2, AES: 0,
    description: "The convening of the Estates-General and fall of the Bastille ended centuries of absolute monarchy, but the constitutional monarchy experiment proved unstable. Aristocratic privilege collapsed amid fiscal crisis and revolutionary ferment."
  },
  {
    jurisdiction: "France",
    regime: "French Revolution",
    startYear: 1792,
    endYear: 1799,
    MAT: 1, CD: 1, CU: 2, MOR: 5,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 5, ONT_S: 5,
    PF: 5, TRB: 4, ENG: 5,
    EPS: 4, AES: 5,
    description: "The radical republic unleashed the Terror, abolished feudalism, and proclaimed universal rights while executing thousands. The Directory's instability paved the way for Napoleon, but the Revolution permanently transformed European politics."
  },
  {
    jurisdiction: "France",
    regime: "Napoleonic Empire",
    startYear: 1800,
    endYear: 1814,
    MAT: 3, CD: 3, CU: 2, MOR: 3,
    PRO: 3, COM: 1, ZS: 4,
    ONT_H: 3, ONT_S: 3,
    PF: 1, TRB: 4, ENG: 5,
    EPS: 0, AES: 4,
    description: "Napoleon centralized the French state, codified law in the Code Napoleon, and conquered much of Europe before his defeat. A meritocratic authoritarian who consolidated revolutionary gains while suppressing political liberty."
  },
  {
    jurisdiction: "France",
    regime: "Restoration",
    startYear: 1815,
    endYear: 1829,
    MAT: 5, CD: 5, CU: 1, MOR: 2,
    PRO: 3, COM: 2, ZS: 3,
    ONT_H: 2, ONT_S: 2,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 2, AES: 0,
    description: "The Bourbon monarchs returned under a limited constitutional charter, but Ultra-royalists pushed to restore pre-revolutionary aristocratic and clerical privilege. Tension between legitimism and liberalism defined the period."
  },
  {
    jurisdiction: "France",
    regime: "July Monarchy",
    startYear: 1830,
    endYear: 1847,
    MAT: 5, CD: 4, CU: 2, MOR: 3,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 3, ONT_S: 2,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 0, AES: 0,
    description: "Louis-Philippe's bourgeois monarchy championed business interests and cautious liberalism after the July Revolution. Industrialization accelerated but the narrow franchise excluded workers, breeding republican and socialist opposition."
  },
  {
    jurisdiction: "France",
    regime: "Second Republic",
    startYear: 1848,
    endYear: 1851,
    MAT: 2, CD: 2, CU: 3, MOR: 4,
    PRO: 3, COM: 3, ZS: 3,
    ONT_H: 4, ONT_S: 4,
    PF: 4, TRB: 3, ENG: 5,
    EPS: 0, AES: 5,
    description: "Universal male suffrage and national workshops represented radical democratic ambitions, but the June Days uprising revealed deep class conflict. Louis-Napoleon's election as president foreshadowed the republic's demise."
  },
  {
    jurisdiction: "France",
    regime: "Second Empire",
    startYear: 1852,
    endYear: 1870,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 3, ZS: 3,
    ONT_H: 3, ONT_S: 2,
    PF: 2, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    description: "Napoleon III modernized Paris, built railways, and pursued an active foreign policy while maintaining authoritarian control that gradually liberalized. Defeat in the Franco-Prussian War brought the regime's sudden collapse."
  },
  {
    jurisdiction: "France",
    regime: "Third Republic Early",
    startYear: 1871,
    endYear: 1899,
    MAT: 3, CD: 2, CU: 3, MOR: 4,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 4, ONT_S: 3,
    PF: 5, TRB: 3, ENG: 4,
    EPS: 0, AES: 0,
    description: "Born from the Paris Commune's ashes, the Third Republic consolidated secular, republican governance through the Dreyfus Affair and laicite laws. Intense partisan conflict between clericals, monarchists, and republicans defined political life."
  },
  {
    jurisdiction: "France",
    regime: "Third Republic Late",
    startYear: 1900,
    endYear: 1939,
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 5, TRB: 3, ENG: 4,
    EPS: 1, AES: 0,
    description: "The Radical Republic championed secularism and colonial expansion while interwar instability saw rapid government turnover and the Popular Front experiment. Rising fascist leagues and pacifism left France ill-prepared for war."
  },
  {
    jurisdiction: "France",
    regime: "Vichy France",
    startYear: 1940,
    endYear: 1944,
    MAT: 4, CD: 5, CU: 5, MOR: 1,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 1, ONT_S: 5,
    PF: 1, TRB: 5, ENG: 4,
    EPS: 2, AES: 2,
    description: "Petain's collaborationist regime embraced authoritarian traditionalism under the motto 'Travail, Famille, Patrie,' actively participating in the deportation of Jews. It represented a reactionary rejection of republican values."
  },
  {
    jurisdiction: "France",
    regime: "Fourth Republic",
    startYear: 1946,
    endYear: 1957,
    MAT: 2, CD: 2, CU: 3, MOR: 4,
    PRO: 4, COM: 5, ZS: 2,
    ONT_H: 4, ONT_S: 3,
    PF: 5, TRB: 2, ENG: 4,
    EPS: 1, AES: 0,
    description: "Post-war reconstruction and European integration proceeded amid chronic governmental instability with 21 prime ministers in 12 years. The Algerian crisis ultimately destroyed the regime and recalled de Gaulle to power."
  },
  {
    jurisdiction: "France",
    regime: "Fifth Republic Gaullist",
    startYear: 1958,
    endYear: 1980,
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 2, ZS: 3,
    ONT_H: 3, ONT_S: 2,
    PF: 4, TRB: 4, ENG: 4,
    EPS: 1, AES: 0,
    description: "De Gaulle's strong presidential republic pursued national grandeur, an independent nuclear deterrent, and dirigiste economic planning. May 1968 challenged the regime's cultural conservatism but Gaullism survived in modified form."
  },
  {
    jurisdiction: "France",
    regime: "Fifth Republic Modern",
    startYear: 1981,
    endYear: 2026,
    MAT: 3, CD: 2, CU: 4, MOR: 4,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 0,
    description: "From Mitterrand's socialist experiment through Chirac, Sarkozy, Hollande, and Macron, France deepened EU integration while grappling with deindustrialization, immigration, and the gilets jaunes movement. The traditional left-right divide fragmented."
  },

  // ===== GERMANY/PRUSSIA =====
  {
    jurisdiction: "Germany/Prussia",
    regime: "Prussian Reform Era",
    startYear: 1789,
    endYear: 1814,
    MAT: 4, CD: 4, CU: 2, MOR: 2,
    PRO: 4, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 2, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    description: "After Prussia's devastating defeat at Jena in 1806, the Stein-Hardenberg reforms modernized the state by abolishing serfdom and reforming the military and education. Reform was driven by crisis rather than ideology, aiming to strengthen the state against Napoleonic France."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "German Confederation",
    startYear: 1815,
    endYear: 1847,
    MAT: 4, CD: 5, CU: 1, MOR: 2,
    PRO: 4, COM: 3, ZS: 3,
    ONT_H: 2, ONT_S: 2,
    PF: 2, TRB: 4, ENG: 2,
    EPS: 2, AES: 0,
    description: "Metternich's conservative order suppressed liberal and nationalist movements through the Carlsbad Decrees and pervasive censorship. The Biedermeier period saw political quietism as Germans retreated into private life under authoritarian surveillance."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "1848 Revolution",
    startYear: 1848,
    endYear: 1849,
    MAT: 3, CD: 3, CU: 3, MOR: 4,
    PRO: 4, COM: 3, ZS: 3,
    ONT_H: 4, ONT_S: 5,
    PF: 4, TRB: 4, ENG: 5,
    EPS: 0, AES: 5,
    description: "The Frankfurt Parliament attempted to create a unified, liberal German nation-state through democratic deliberation, but failed when Frederick William IV refused the crown. The revolution's defeat entrenched the power of the Prussian military-aristocratic elite."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "Bismarck Era",
    startYear: 1850,
    endYear: 1890,
    MAT: 3, CD: 4, CU: 2, MOR: 2,
    PRO: 3, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 2,
    PF: 4, TRB: 4, ENG: 4,
    EPS: 0, AES: 0,
    description: "Bismarck unified Germany through 'blood and iron' while introducing pioneering social insurance to co-opt the working class. His Realpolitik combined authoritarian governance with pragmatic welfare-state building and Kulturkampf against Catholic influence."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "Wilhelmine",
    startYear: 1891,
    endYear: 1913,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 3,
    PF: 4, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    description: "Kaiser Wilhelm II pursued Weltpolitik and a naval arms race with Britain while the SPD became Europe's largest socialist party. An aggressive, militaristic national mood combined with rapid industrialization and growing social tensions."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "WWI Germany",
    startYear: 1914,
    endYear: 1918,
    MAT: 2, CD: 5, CU: 1, MOR: 2,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 2, ONT_S: 5,
    PF: 3, TRB: 5, ENG: 5,
    EPS: 1, AES: 4,
    description: "The Hindenburg-Ludendorff military dictatorship directed total war while the home front suffered severe deprivation and the Burgfrieden political truce frayed. Defeat, revolution, and the Kaiser's abdication shattered the imperial order."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "Weimar Republic",
    startYear: 1919,
    endYear: 1932,
    MAT: 3, CD: 2, CU: 4, MOR: 4,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 4, ONT_S: 4,
    PF: 5, TRB: 3, ENG: 5,
    EPS: 0, AES: 5,
    description: "Germany's first democracy produced remarkable cultural flowering and a progressive constitution, but was destabilized by hyperinflation, the Versailles burden, and extremist violence from both left and right. Intense partisan fragmentation made governance nearly impossible."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "Nazi Germany",
    startYear: 1933,
    endYear: 1945,
    MAT: 3, CD: 5, CU: 5, MOR: 1,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 1, ONT_S: 2,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 3, AES: 4,
    description: "The totalitarian racial state under Hitler pursued genocidal antisemitism, aggressive expansionism, and the complete destruction of democratic institutions. The Holocaust and World War II represented the catastrophic nadir of European civilization."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "Occupied Germany",
    startYear: 1945,
    endYear: 1948,
    MAT: 3, CD: 2, CU: 3, MOR: 4,
    PRO: 3, COM: 4, ZS: 2,
    ONT_H: 3, ONT_S: 5,
    PF: 2, TRB: 1, ENG: 3,
    EPS: 0, AES: 0,
    description: "Allied occupation imposed denazification, dismantled military industry, and laid the groundwork for democratic reconstruction. The emerging Cold War split Germany into eastern and western zones with fundamentally different political trajectories."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "West Germany/Bonn Republic",
    startYear: 1949,
    endYear: 1989,
    MAT: 3, CD: 3, CU: 3, MOR: 4,
    PRO: 5, COM: 5, ZS: 2,
    ONT_H: 3, ONT_S: 2,
    PF: 4, TRB: 2, ENG: 4,
    EPS: 1, AES: 0,
    description: "The social market economy produced the Wirtschaftswunder while the Basic Law enshrined strong constitutional protections and consensus-based governance. Brandt's Ostpolitik normalized relations with the East, and West Germany became the anchor of European integration."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "East Germany/DDR",
    startYear: 1949,
    endYear: 1989,
    MAT: 1, CD: 4, CU: 5, MOR: 3,
    PRO: 1, COM: 1, ZS: 4,
    ONT_H: 4, ONT_S: 3,
    PF: 5, TRB: 4, ENG: 4,
    EPS: 1, AES: 1,
    description: "The Soviet-backed socialist state maintained rigid ideological conformity through the Stasi surveillance apparatus. Despite rhetoric of worker emancipation, the DDR was culturally conservative, authoritarian, and economically stagnant."
  },
  {
    jurisdiction: "Germany/Prussia",
    regime: "Reunified Germany",
    startYear: 1990,
    endYear: 2026,
    MAT: 3, CD: 2, CU: 4, MOR: 4,
    PRO: 5, COM: 5, ZS: 2,
    ONT_H: 4, ONT_S: 2,
    PF: 4, TRB: 2, ENG: 4,
    EPS: 0, AES: 0,
    description: "The Berlin Republic anchored European integration, navigated reunification's social costs, and opened its doors during the 2015 refugee crisis. Strong proceduralism and consensus politics persisted even as the AfD challenged the post-war settlement."
  },

  // ===== RUSSIA/USSR =====
  {
    jurisdiction: "Russia/USSR",
    regime: "Tsarist Russia Late Catherine/Alexander I",
    startYear: 1789,
    endYear: 1825,
    MAT: 5, CD: 5, CU: 1, MOR: 2,
    PRO: 2, COM: 1, ZS: 4,
    ONT_H: 2, ONT_S: 2,
    PF: 1, TRB: 4, ENG: 2,
    EPS: 2, AES: 0,
    description: "Catherine the Great's Enlightenment pretensions gave way to reaction after the French Revolution, and Alexander I oscillated between liberal reform and mystical conservatism. Serfdom remained the bedrock of an autocratic social order."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Nicholas I",
    startYear: 1826,
    endYear: 1855,
    MAT: 5, CD: 5, CU: 1, MOR: 2,
    PRO: 3, COM: 1, ZS: 4,
    ONT_H: 1, ONT_S: 2,
    PF: 1, TRB: 5, ENG: 2,
    EPS: 2, AES: 0,
    description: "The 'Gendarme of Europe' crushed the Decembrist revolt and enforced Official Nationality (Orthodoxy, Autocracy, Nationality) as state doctrine. Serfdom, censorship, and military repression defined a regime deeply hostile to change."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Great Reforms",
    startYear: 1856,
    endYear: 1881,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 4, COM: 3, ZS: 3,
    ONT_H: 3, ONT_S: 4,
    PF: 2, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "Alexander II emancipated the serfs in 1861, established elected zemstva councils, and reformed the judiciary and military. These reforms from above opened Russian society but were cut short by his assassination by revolutionary terrorists."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Reaction/Late Tsarist",
    startYear: 1882,
    endYear: 1904,
    MAT: 4, CD: 5, CU: 1, MOR: 2,
    PRO: 2, COM: 1, ZS: 4,
    ONT_H: 1, ONT_S: 3,
    PF: 1, TRB: 5, ENG: 3,
    EPS: 2, AES: 0,
    description: "Alexander III and Nicholas II reversed reforms, intensified Russification, and oversaw pogroms against Jewish communities. Rapid industrialization under Witte created a volatile urban proletariat while the autocracy remained unreconstructed."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Revolution Era",
    startYear: 1905,
    endYear: 1917,
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2, ZS: 4,
    ONT_H: 3, ONT_S: 5,
    PF: 4, TRB: 4, ENG: 5,
    EPS: 3, AES: 4,
    description: "The 1905 Revolution forced the creation of the Duma, but Nicholas II's intransigence and WWI's catastrophic toll brought the regime to collapse. Competing visions from liberals, socialists, and monarchists made this an era of radical uncertainty."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Soviet Early/Lenin",
    startYear: 1918,
    endYear: 1928,
    MAT: 1, CD: 2, CU: 2, MOR: 4,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 5, ONT_S: 5,
    PF: 1, TRB: 4, ENG: 5,
    EPS: 4, AES: 5,
    description: "War communism, civil war, and the New Economic Policy defined the revolutionary state's turbulent first decade. Lenin's Bolsheviks pursued utopian transformation of society while ruthlessly crushing all opposition."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Stalin",
    startYear: 1929,
    endYear: 1953,
    MAT: 1, CD: 2, CU: 5, MOR: 1,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 2, ONT_S: 3,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 1, AES: 4,
    description: "Forced collectivization, breakneck industrialization, the Great Purges, and victory in WWII were achieved through totalitarian terror and mass death. Stalin built a cult of personality atop a system of labor camps, deportations, and paranoid state violence."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Khrushchev Thaw",
    startYear: 1954,
    endYear: 1964,
    MAT: 1, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 3, ZS: 4,
    ONT_H: 4, ONT_S: 3,
    PF: 3, TRB: 4, ENG: 4,
    EPS: 1, AES: 5,
    description: "Khrushchev's Secret Speech denounced Stalin's crimes and inaugurated a partial cultural and political thaw. The space race showcased Soviet ambition, but the Hungarian intervention and Cuban Missile Crisis revealed the system's aggressive instincts."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Brezhnev Stagnation",
    startYear: 1965,
    endYear: 1984,
    MAT: 1, CD: 4, CU: 4, MOR: 3,
    PRO: 2, COM: 2, ZS: 4,
    ONT_H: 3, ONT_S: 2,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    description: "The Brezhnev era prioritized stability and detente while economic growth slowed and the dissident movement emerged. The invasion of Afghanistan and suppression of Prague Spring demonstrated continued imperial ambitions despite internal decay."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Gorbachev/Collapse",
    startYear: 1985,
    endYear: 1991,
    MAT: 3, CD: 3, CU: 3, MOR: 4,
    PRO: 3, COM: 4, ZS: 3,
    ONT_H: 4, ONT_S: 5,
    PF: 3, TRB: 3, ENG: 5,
    EPS: 0, AES: 5,
    description: "Glasnost and perestroika attempted to reform the Soviet system but unleashed forces that dissolved it entirely. Gorbachev's vision of democratic socialism proved incompatible with the accumulated contradictions of the Soviet empire."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Yeltsin",
    startYear: 1992,
    endYear: 1999,
    MAT: 5, CD: 2, CU: 3, MOR: 3,
    PRO: 2, COM: 3, ZS: 4,
    ONT_H: 2, ONT_S: 5,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 4, AES: 3,
    description: "Shock therapy privatization created oligarchs while impoverishing millions, the 1993 constitutional crisis saw tanks shell parliament, and the Chechen wars ravaged the Caucasus. Democratic institutions remained fragile amid economic chaos and state decay."
  },
  {
    jurisdiction: "Russia/USSR",
    regime: "Putin Era",
    startYear: 2000,
    endYear: 2026,
    MAT: 4, CD: 5, CU: 4, MOR: 2,
    PRO: 2, COM: 1, ZS: 5,
    ONT_H: 1, ONT_S: 3,
    PF: 4, TRB: 5, ENG: 4,
    EPS: 3, AES: 4,
    description: "Putin consolidated power through managed democracy, resource nationalism, and aggressive foreign policy culminating in the invasion of Ukraine. Traditional values, Orthodox nationalism, and geopolitical confrontation with the West defined an increasingly authoritarian state."
  },

  // ===== SPAIN =====
  {
    jurisdiction: "Spain",
    regime: "Bourbon Spain/Napoleonic",
    startYear: 1789,
    endYear: 1813,
    MAT: 4, CD: 5, CU: 1, MOR: 2,
    PRO: 2, COM: 1, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 2, TRB: 4, ENG: 4,
    EPS: 2, AES: 4,
    description: "Napoleon's invasion provoked fierce guerrilla resistance and the liberal Cadiz Constitution of 1812, while the old Bourbon order collapsed. Spain became a battleground between Enlightenment reform and traditionalist Catholic reaction."
  },
  {
    jurisdiction: "Spain",
    regime: "Liberal-Absolutist struggle",
    startYear: 1814,
    endYear: 1833,
    MAT: 4, CD: 5, CU: 1, MOR: 2,
    PRO: 2, COM: 1, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 3, TRB: 4, ENG: 4,
    EPS: 2, AES: 4,
    description: "Ferdinand VII abolished the liberal constitution and restored absolute monarchy, provoking the Riego revolt and the Carlist succession crisis. Spain oscillated violently between liberalism and absolutism with no stable settlement."
  },
  {
    jurisdiction: "Spain",
    regime: "Isabella/Moderate Monarchy",
    startYear: 1834,
    endYear: 1868,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 3, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "Isabella II's reign saw moderate liberals consolidate power through the desamortizacion (church land sales) and slow modernization. Military pronunciamientos remained the primary mechanism of political change in a still largely agrarian society."
  },
  {
    jurisdiction: "Spain",
    regime: "Sexenio/Restoration",
    startYear: 1869,
    endYear: 1897,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 4, ZS: 3,
    ONT_H: 3, ONT_S: 2,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "After a brief First Republic, Canovas designed the Restoration system with its turno pacifico alternation between Liberal and Conservative parties. Managed elections provided stability but excluded workers, regionalists, and republicans from power."
  },
  {
    jurisdiction: "Spain",
    regime: "Crisis/Primo",
    startYear: 1898,
    endYear: 1930,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 3, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    description: "The 1898 colonial disaster triggered a national identity crisis, and Primo de Rivera's dictatorship attempted authoritarian modernization. The Restoration system's legitimacy collapsed amid labor unrest, regional nationalism, and military interventionism."
  },
  {
    jurisdiction: "Spain",
    regime: "Second Republic",
    startYear: 1931,
    endYear: 1936,
    MAT: 2, CD: 1, CU: 4, MOR: 4,
    PRO: 4, COM: 3, ZS: 3,
    ONT_H: 4, ONT_S: 4,
    PF: 5, TRB: 3, ENG: 5,
    EPS: 0, AES: 5,
    description: "Radical democratic reform tackled land redistribution, church-state separation, regional autonomy, and military reform simultaneously. Intense polarization between left and right, anticlericals and Catholics, centralists and regionalists made compromise impossible."
  },
  {
    jurisdiction: "Spain",
    regime: "Civil War/Franco",
    startYear: 1936,
    endYear: 1959,
    MAT: 4, CD: 5, CU: 5, MOR: 2,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 1, ONT_S: 3,
    PF: 5, TRB: 5, ENG: 4,
    EPS: 2, AES: 4,
    description: "Franco's National-Catholic regime, born from civil war, imposed autarky, crushed regional identities, and enforced a reactionary social order. Mass repression, international isolation, and economic hardship characterized the early Franco decades."
  },
  {
    jurisdiction: "Spain",
    regime: "Late Franco",
    startYear: 1960,
    endYear: 1975,
    MAT: 5, CD: 5, CU: 4, MOR: 2,
    PRO: 2, COM: 2, ZS: 3,
    ONT_H: 2, ONT_S: 2,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 1, AES: 1,
    description: "Opus Dei technocrats drove an economic miracle while the regime cautiously opened to tourism and foreign investment. Political repression continued but social transformation and growing opposition signaled the regime's approaching end."
  },
  {
    jurisdiction: "Spain",
    regime: "Transition",
    startYear: 1976,
    endYear: 1982,
    MAT: 3, CD: 3, CU: 4, MOR: 4,
    PRO: 5, COM: 5, ZS: 2,
    ONT_H: 4, ONT_S: 3,
    PF: 4, TRB: 2, ENG: 5,
    EPS: 1, AES: 0,
    description: "Suarez and King Juan Carlos navigated democratization through consensus, producing the 1978 Constitution and the Estado de las Autonomias. The transition's spirit of consenso became a founding myth of Spanish democracy despite the 1981 coup attempt."
  },
  {
    jurisdiction: "Spain",
    regime: "PSOE/PP Democracy",
    startYear: 1983,
    endYear: 2007,
    MAT: 3, CD: 2, CU: 4, MOR: 4,
    PRO: 4, COM: 4, ZS: 2,
    ONT_H: 4, ONT_S: 2,
    PF: 4, TRB: 2, ENG: 4,
    EPS: 0, AES: 0,
    description: "Gonzalez modernized Spain and joined the EU, Aznar pursued economic liberalization and atlanticism, and both oversaw rapid growth and social transformation. Spain became a confident European democracy with a booming economy."
  },
  {
    jurisdiction: "Spain",
    regime: "Crisis Spain",
    startYear: 2008,
    endYear: 2026,
    MAT: 3, CD: 3, CU: 4, MOR: 4,
    PRO: 4, COM: 3, ZS: 3,
    ONT_H: 3, ONT_S: 4,
    PF: 5, TRB: 3, ENG: 5,
    EPS: 0, AES: 3,
    description: "The financial crisis, Indignados movement, Catalan independence crisis, and rise of Podemos and Vox shattered the two-party system. Spain grappled with austerity, territorial tensions, and a new generation's disillusionment with the transition settlement."
  },

  // ===== ITALY =====
  {
    jurisdiction: "Italy",
    regime: "Italian States/Napoleonic",
    startYear: 1789,
    endYear: 1814,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2, ZS: 3,
    ONT_H: 3, ONT_S: 4,
    PF: 2, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    description: "Napoleon's invasion swept away the old Italian states and introduced revolutionary legal codes, administrative centralization, and the idea of national unity. Jacobin republics briefly flourished before giving way to satellite kingdoms."
  },
  {
    jurisdiction: "Italy",
    regime: "Restoration/Risorgimento",
    startYear: 1815,
    endYear: 1860,
    MAT: 3, CD: 3, CU: 3, MOR: 4,
    PRO: 3, COM: 3, ZS: 3,
    ONT_H: 4, ONT_S: 4,
    PF: 4, TRB: 4, ENG: 5,
    EPS: 0, AES: 5,
    description: "Mazzini's republican idealism and Cavour's pragmatic diplomacy drove the Risorgimento, culminating in Garibaldi's expedition and Italian unification. A romantic nationalist project that united a peninsula divided by foreign powers, local identities, and the papacy."
  },
  {
    jurisdiction: "Italy",
    regime: "Liberal Italy",
    startYear: 1861,
    endYear: 1913,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 4, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "United Italy faced the Southern Question, mass emigration, and transformismo politics where shifting parliamentary coalitions blurred ideological lines. Giolitti's era brought limited democratization and industrialization, concentrated overwhelmingly in the north."
  },
  {
    jurisdiction: "Italy",
    regime: "WWI Italy/Crisis",
    startYear: 1914,
    endYear: 1921,
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2, ZS: 5,
    ONT_H: 2, ONT_S: 5,
    PF: 4, TRB: 4, ENG: 5,
    EPS: 3, AES: 4,
    description: "Italy's entry into WWI divided the nation; the 'mutilated victory' fueled nationalist resentment and the biennio rosso saw factory occupations and rural unrest. The liberal state proved incapable of managing the post-war crisis, opening the door to fascism."
  },
  {
    jurisdiction: "Italy",
    regime: "Fascist Italy",
    startYear: 1922,
    endYear: 1943,
    MAT: 3, CD: 5, CU: 5, MOR: 2,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 2, ONT_S: 3,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 3, AES: 4,
    description: "Mussolini's fascist regime pioneered totalitarian mass politics, corporatist economics, and imperial aggression in Ethiopia and Albania. The alliance with Nazi Germany and disastrous military performance led to invasion, civil war, and the regime's collapse."
  },
  {
    jurisdiction: "Italy",
    regime: "Post-war Republic",
    startYear: 1946,
    endYear: 1968,
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 5, ZS: 2,
    ONT_H: 3, ONT_S: 2,
    PF: 5, TRB: 3, ENG: 4,
    EPS: 1, AES: 0,
    description: "Christian Democracy dominated post-war Italy through coalition-building and Cold War anticommunism while the economic miracle transformed a peasant society. The PCI remained Western Europe's largest communist party but was permanently excluded from national government."
  },
  {
    jurisdiction: "Italy",
    regime: "Years of Lead",
    startYear: 1969,
    endYear: 1983,
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 4, ZS: 4,
    ONT_H: 3, ONT_S: 4,
    PF: 5, TRB: 3, ENG: 5,
    EPS: 1, AES: 4,
    description: "Left-wing and right-wing terrorism, the Aldo Moro kidnapping, and the strategy of tension destabilized Italian democracy. Berlinguer's compromesso storico sought to bridge the DC-PCI divide amid a climate of political violence and social upheaval."
  },
  {
    jurisdiction: "Italy",
    regime: "Craxi/First Republic End",
    startYear: 1984,
    endYear: 1993,
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 2, COM: 4, ZS: 3,
    ONT_H: 2, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 1, AES: 3,
    description: "Craxi's Socialist-led coalitions modernized Italy's image but systemic corruption was exposed by the Tangentopoli investigations. The Mani Pulite judicial revolution destroyed the entire post-war party system in a matter of months."
  },
  {
    jurisdiction: "Italy",
    regime: "Second Republic",
    startYear: 1994,
    endYear: 2012,
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 4, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 3, AES: 3,
    description: "Berlusconi's media empire and personal politics dominated the Second Republic, alternating with center-left coalitions. Italy joined the eurozone but struggled with low growth, high debt, and institutional reform that never quite materialized."
  },
  {
    jurisdiction: "Italy",
    regime: "Populist Italy",
    startYear: 2013,
    endYear: 2026,
    MAT: 3, CD: 4, CU: 3, MOR: 3,
    PRO: 3, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 4, TRB: 4, ENG: 5,
    EPS: 3, AES: 3,
    description: "The Five Star Movement, Salvini's League, and Meloni's Brothers of Italy disrupted traditional politics with anti-establishment populism. Migration, Euroscepticism, and economic stagnation fueled a rightward turn and growing distrust of institutions."
  },

  // ===== AUSTRIA/AUSTRIA-HUNGARY =====
  {
    jurisdiction: "Austria/Austria-Hungary",
    regime: "Habsburg Enlightened Absolutism",
    startYear: 1789,
    endYear: 1814,
    MAT: 4, CD: 4, CU: 2, MOR: 2,
    PRO: 3, COM: 2, ZS: 3,
    ONT_H: 3, ONT_S: 2,
    PF: 1, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "The legacy of Joseph II's top-down reforms persisted as Austria fought the Revolutionary and Napoleonic Wars under Francis I. Enlightened absolutism gave way to wartime mobilization and conservative retrenchment against French revolutionary ideas."
  },
  {
    jurisdiction: "Austria/Austria-Hungary",
    regime: "Metternich System",
    startYear: 1815,
    endYear: 1847,
    MAT: 4, CD: 5, CU: 1, MOR: 2,
    PRO: 4, COM: 2, ZS: 3,
    ONT_H: 1, ONT_S: 1,
    PF: 1, TRB: 4, ENG: 2,
    EPS: 2, AES: 0,
    description: "Metternich constructed a European conservative order based on legitimacy, balance of power, and suppression of nationalism and liberalism. Domestically, censorship and secret police maintained the multinational empire's fragile cohesion."
  },
  {
    jurisdiction: "Austria/Austria-Hungary",
    regime: "1848/Neo-Absolutism",
    startYear: 1848,
    endYear: 1866,
    MAT: 4, CD: 4, CU: 2, MOR: 2,
    PRO: 3, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 2, TRB: 4, ENG: 4,
    EPS: 1, AES: 0,
    description: "The 1848 revolution was crushed by military force, and the Bach system reimposed centralized absolutism. Defeat at Koniggratz in 1866 ended Austrian influence in Germany and forced the empire to renegotiate its internal structure."
  },
  {
    jurisdiction: "Austria/Austria-Hungary",
    regime: "Austria-Hungary Dual Monarchy",
    startYear: 1867,
    endYear: 1913,
    MAT: 4, CD: 4, CU: 3, MOR: 3,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 2, ONT_S: 3,
    PF: 4, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    description: "The 1867 Ausgleich created the Dual Monarchy, granting Hungary autonomy while leaving other nationalities dissatisfied. A constitutional framework managed competing national, religious, and class interests with increasing difficulty as Pan-Slavism and other movements grew."
  },
  {
    jurisdiction: "Austria/Austria-Hungary",
    regime: "WWI/Collapse",
    startYear: 1914,
    endYear: 1918,
    MAT: 3, CD: 4, CU: 2, MOR: 2,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 2, ONT_S: 5,
    PF: 3, TRB: 5, ENG: 5,
    EPS: 1, AES: 4,
    description: "The assassination of Franz Ferdinand triggered a war that ultimately dissolved the Habsburg Empire into successor nation-states. Military defeat, ethnic fragmentation, and revolutionary upheaval ended six centuries of Habsburg rule."
  },
  {
    jurisdiction: "Austria/Austria-Hungary",
    regime: "First Republic",
    startYear: 1919,
    endYear: 1933,
    MAT: 2, CD: 3, CU: 3, MOR: 3,
    PRO: 4, COM: 3, ZS: 4,
    ONT_H: 3, ONT_S: 4,
    PF: 5, TRB: 4, ENG: 5,
    EPS: 0, AES: 5,
    description: "Red Vienna's municipal socialism confronted rural Christian Social conservatism in an increasingly polarized republic. Paramilitary organizations on both sides made political violence endemic, undermining democratic institutions."
  },
  {
    jurisdiction: "Austria/Austria-Hungary",
    regime: "Austrofascism/Anschluss",
    startYear: 1934,
    endYear: 1945,
    MAT: 4, CD: 5, CU: 5, MOR: 1,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 1, ONT_S: 5,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 2, AES: 4,
    description: "Dollfuss's authoritarian Catholic corporatist state suppressed both socialists and Nazis before Hitler's 1938 Anschluss absorbed Austria into the Third Reich. Austrians participated extensively in Nazi crimes while later claiming victim status."
  },
  {
    jurisdiction: "Austria/Austria-Hungary",
    regime: "Second Republic Consensus",
    startYear: 1945,
    endYear: 1986,
    MAT: 3, CD: 3, CU: 3, MOR: 4,
    PRO: 5, COM: 5, ZS: 2,
    ONT_H: 4, ONT_S: 2,
    PF: 4, TRB: 2, ENG: 3,
    EPS: 1, AES: 0,
    description: "The grand coalition and Sozialpartnerschaft (social partnership) between labor and business created one of Europe's most consensual and prosperous democracies. Neutrality, the Proporz system, and institutional cooperation defined a deliberately depoliticized society."
  },
  {
    jurisdiction: "Austria/Austria-Hungary",
    regime: "Modern Austria",
    startYear: 1987,
    endYear: 2026,
    MAT: 3, CD: 3, CU: 3, MOR: 4,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 0,
    description: "Haider's FPO breakthrough shattered the cozy consensus, and EU accession in 1995 integrated Austria into European structures. Immigration debates, the FPO's recurring strength, and coalition experimentation marked a more contested political landscape."
  },

  // ===== OTTOMAN EMPIRE/TURKEY =====
  {
    jurisdiction: "Ottoman Empire/Turkey",
    regime: "Late Ottoman",
    startYear: 1789,
    endYear: 1807,
    MAT: 4, CD: 5, CU: 3, MOR: 2,
    PRO: 2, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 3,
    PF: 1, TRB: 4, ENG: 2,
    EPS: 2, AES: 0,
    description: "Sultan Selim III attempted to modernize the military along European lines, but Janissary resistance to reform culminated in his deposition. The empire faced mounting pressure from Russian expansion and internal centrifugal forces."
  },
  {
    jurisdiction: "Ottoman Empire/Turkey",
    regime: "Tanzimat",
    startYear: 1808,
    endYear: 1876,
    MAT: 4, CD: 4, CU: 3, MOR: 3,
    PRO: 4, COM: 3, ZS: 3,
    ONT_H: 3, ONT_S: 4,
    PF: 2, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "The Tanzimat reforms modernized Ottoman law, administration, and education, proclaiming equality for all subjects regardless of religion. These top-down reforms aimed to save the empire by creating a common Ottoman citizenship, but satisfied neither conservatives nor nationalists."
  },
  {
    jurisdiction: "Ottoman Empire/Turkey",
    regime: "Hamidian Era",
    startYear: 1877,
    endYear: 1907,
    MAT: 4, CD: 5, CU: 2, MOR: 2,
    PRO: 2, COM: 1, ZS: 4,
    ONT_H: 2, ONT_S: 3,
    PF: 1, TRB: 5, ENG: 3,
    EPS: 2, AES: 0,
    description: "Abdul Hamid II suspended the constitution, ruled autocratically, and promoted pan-Islamism as imperial ideology while modernizing infrastructure. The Hamidian massacres of Armenians foreshadowed the genocide to come."
  },
  {
    jurisdiction: "Ottoman Empire/Turkey",
    regime: "Young Turks/WWI",
    startYear: 1908,
    endYear: 1918,
    MAT: 3, CD: 5, CU: 5, MOR: 1,
    PRO: 2, COM: 1, ZS: 5,
    ONT_H: 2, ONT_S: 5,
    PF: 1, TRB: 5, ENG: 5,
    EPS: 3, AES: 4,
    description: "The Committee of Union and Progress restored the constitution then descended into authoritarian Turkish nationalism, entering WWI on Germany's side. The Armenian Genocide of 1915 was carried out amid military defeat and the empire's dissolution."
  },
  {
    jurisdiction: "Ottoman Empire/Turkey",
    regime: "Kemalist Republic",
    startYear: 1919,
    endYear: 1937,
    MAT: 3, CD: 3, CU: 5, MOR: 3,
    PRO: 3, COM: 1, ZS: 3,
    ONT_H: 4, ONT_S: 4,
    PF: 1, TRB: 4, ENG: 5,
    EPS: 0, AES: 5,
    description: "Ataturk's revolutionary republic abolished the caliphate, adopted the Latin alphabet, and pursued radical westernization and secularization. A single-party authoritarian modernizer who forcibly transformed Turkish society from the top down."
  },
  {
    jurisdiction: "Ottoman Empire/Turkey",
    regime: "Multi-party Turkey",
    startYear: 1938,
    endYear: 1959,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 3, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    description: "Turkey transitioned to multi-party democracy with Inonu's CHP yielding power to Menderes's Democrat Party in 1950. Rural conservatism challenged Kemalist secularism as democratization allowed suppressed religious and traditional sentiments to resurface."
  },
  {
    jurisdiction: "Ottoman Empire/Turkey",
    regime: "Coup/Instability Era",
    startYear: 1960,
    endYear: 1979,
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 4,
    PF: 4, TRB: 4, ENG: 5,
    EPS: 1, AES: 4,
    description: "Three military coups in 1960, 1971, and 1980 punctuated civilian politics as left-right political violence claimed thousands of lives. The military saw itself as guardian of the Kemalist secular republic against both Islamism and communism."
  },
  {
    jurisdiction: "Ottoman Empire/Turkey",
    regime: "Ozal/Secular Republic",
    startYear: 1980,
    endYear: 2001,
    MAT: 4, CD: 3, CU: 2, MOR: 3,
    PRO: 3, COM: 3, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 3, TRB: 3, ENG: 4,
    EPS: 1, AES: 0,
    description: "Ozal's economic liberalization opened Turkey to global markets while the military maintained tutelage over politics and the Kurdish conflict intensified. Secular-Islamist tensions simmered as Welfare Party governments were repeatedly forced from power."
  },
  {
    jurisdiction: "Ottoman Empire/Turkey",
    regime: "Erdogan Era",
    startYear: 2002,
    endYear: 2026,
    MAT: 3, CD: 5, CU: 2, MOR: 2,
    PRO: 2, COM: 1, ZS: 4,
    ONT_H: 2, ONT_S: 3,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 3, AES: 4,
    description: "The AKP initially pursued EU-oriented democratization but shifted toward authoritarian Islamist nationalism after the 2013 Gezi protests and 2016 coup attempt. Erdogan concentrated power in a presidential system, purged opponents, and reasserted Turkish influence regionally."
  },

  // ===== POLAND =====
  {
    jurisdiction: "Poland",
    regime: "Partition Era",
    startYear: 1789,
    endYear: 1830,
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2, ZS: 4,
    ONT_H: 3, ONT_S: 5,
    PF: 3, TRB: 5, ENG: 4,
    EPS: 1, AES: 5,
    description: "Poland disappeared from the map through the Third Partition, briefly revived as Napoleon's Duchy of Warsaw, then was reconstituted as Congress Poland under Russian control. The May 3rd Constitution's promise of reform was extinguished by partition."
  },
  {
    jurisdiction: "Poland",
    regime: "November/January Uprisings",
    startYear: 1831,
    endYear: 1863,
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 1, ZS: 5,
    ONT_H: 3, ONT_S: 5,
    PF: 3, TRB: 5, ENG: 5,
    EPS: 3, AES: 5,
    description: "Two major national uprisings against Russian rule were crushed with severe repression, driving Polish nationalism into exile and romantic martyrdom. The messianic idea of Poland as 'Christ of Nations' sustained the independence cause through decades of defeat."
  },
  {
    jurisdiction: "Poland",
    regime: "Organic Work/Positivism",
    startYear: 1864,
    endYear: 1913,
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 4, COM: 3, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 0, AES: 2,
    description: "After the failed January Uprising, Polish intellectuals pursued 'organic work' — economic development, education, and cultural preservation rather than armed revolt. Positivism replaced romanticism as the dominant intellectual framework for national survival."
  },
  {
    jurisdiction: "Poland",
    regime: "Second Republic",
    startYear: 1918,
    endYear: 1926,
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 4, COM: 3, ZS: 3,
    ONT_H: 4, ONT_S: 3,
    PF: 5, TRB: 4, ENG: 5,
    EPS: 1, AES: 5,
    description: "Reborn Poland faced the challenge of integrating three partition zones, large national minorities, and a war with Soviet Russia. Intense democratic competition and the visionary energy of independence coexisted with ethnic tensions and economic difficulties."
  },
  {
    jurisdiction: "Poland",
    regime: "Sanacja/Pilsudski",
    startYear: 1926,
    endYear: 1939,
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2, ZS: 4,
    ONT_H: 2, ONT_S: 3,
    PF: 2, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    description: "Pilsudski's May 1926 coup established authoritarian 'sanation' rule that hollowed out democratic institutions while maintaining a parliamentary facade. The regime grew more repressive after Pilsudski's death as Poland faced existential threats from both Germany and the Soviet Union."
  },
  {
    jurisdiction: "Poland",
    regime: "WWII/Occupation",
    startYear: 1939,
    endYear: 1944,
    MAT: 3, CD: 5, CU: 5, MOR: 1,
    PRO: 1, COM: 1, ZS: 5,
    ONT_H: 1, ONT_S: 5,
    PF: 2, TRB: 5, ENG: 5,
    EPS: 3, AES: 4,
    description: "Nazi occupation destroyed Polish statehood, exterminated nearly all Polish Jews in the Holocaust, and killed millions of ethnic Poles through terror, slave labor, and deliberate cultural destruction. The resistance maintained a functioning underground state and army."
  },
  {
    jurisdiction: "Poland",
    regime: "Stalinist Poland",
    startYear: 1945,
    endYear: 1956,
    MAT: 1, CD: 4, CU: 5, MOR: 3,
    PRO: 1, COM: 1, ZS: 4,
    ONT_H: 4, ONT_S: 3,
    PF: 5, TRB: 4, ENG: 4,
    EPS: 1, AES: 1,
    description: "Soviet-imposed communism nationalized industry, collectivized agriculture, and suppressed the Catholic Church and all opposition. The Stalinist period saw show trials, censorship, and the forced adoption of socialist realism in culture."
  },
  {
    jurisdiction: "Poland",
    regime: "Gomulka/Gierek",
    startYear: 1957,
    endYear: 1980,
    MAT: 1, CD: 4, CU: 4, MOR: 3,
    PRO: 2, COM: 2, ZS: 4,
    ONT_H: 3, ONT_S: 3,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    description: "Gomulka's 'Polish road to socialism' allowed slightly more cultural freedom, but the antisemitic 1968 campaign and 1970 worker massacres revealed the regime's brutality. Gierek borrowed heavily from the West, creating temporary prosperity followed by economic crisis."
  },
  {
    jurisdiction: "Poland",
    regime: "Solidarity/Transition",
    startYear: 1981,
    endYear: 1997,
    MAT: 4, CD: 3, CU: 3, MOR: 4,
    PRO: 4, COM: 4, ZS: 3,
    ONT_H: 4, ONT_S: 5,
    PF: 4, TRB: 3, ENG: 5,
    EPS: 0, AES: 5,
    description: "The Solidarity movement, martial law, the Round Table negotiations, and Balcerowicz's shock therapy transformed Poland from communist dictatorship to market democracy. A remarkable negotiated revolution driven by worker solidarity, Catholic moral authority, and democratic aspiration."
  },
  {
    jurisdiction: "Poland",
    regime: "PiS Poland",
    startYear: 1998,
    endYear: 2026,
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 2, ZS: 3,
    ONT_H: 3, ONT_S: 3,
    PF: 5, TRB: 4, ENG: 5,
    EPS: 2, AES: 4,
    description: "EU accession brought rapid economic growth, but PiS's illiberal turn challenged judicial independence and media freedom while championing Catholic social values. Poland became a key battleground between liberal European norms and national-conservative sovereignty claims."
  },
];
