import type { RegimePeriod } from "./jurisdictions-europe1.js";

export const AMERICAS: RegimePeriod[] = [
  // ──────────────────────────────────────────────
  // 1. UNITED STATES OF AMERICA
  // ──────────────────────────────────────────────
  {
    jurisdiction: "USA",
    regime: "Federalist Era",
    startYear: 1789,
    endYear: 1800,
    description:
      "Washington and Adams established constitutional governance under Federalist dominance, culminating in the controversial Alien and Sedition Acts.",
    MAT: 5, CD: 3, CU: 3, MOR: 3,
    PRO: 5, COM: 4,
    ZS: 3, ONT_H: 3, ONT_S: 2,
    PF: 3, TRB: 3, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "USA",
    regime: "Jeffersonian",
    startYear: 1801,
    endYear: 1823,
    description:
      "Republican ascendancy under Jefferson and successors expanded the nation through the Louisiana Purchase and weathered the War of 1812.",
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 4, COM: 4,
    ZS: 2, ONT_H: 4, ONT_S: 2,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 0, AES: 2,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "USA",
    regime: "Jacksonian Democracy",
    startYear: 1824,
    endYear: 1849,
    description:
      "Mass white-male democracy emerged alongside Indian Removal and Manifest Destiny, driven by populist energy and territorial ambition.",
    MAT: 4, CD: 4, CU: 2, MOR: 2,
    PRO: 3, COM: 3,
    ZS: 4, ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 4, ENG: 4,
    EPS: 3, AES: 3,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.16, religious: 0.41, class: 0.05, ideological: 0.34, gender: 0.09, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "USA",
    regime: "Sectional Crisis",
    startYear: 1850,
    endYear: 1860,
    description:
      "Escalating conflict over slavery produced the Compromise of 1850, Kansas-Nebraska Act, and Dred Scott decision, making civil war increasingly inevitable.",
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 2,
    ZS: 5, ONT_H: 2, ONT_S: 4,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.95, ethnic_racial: 0.05, religious: 0.53, class: 0.05, ideological: 0.43, gender: 0.1, political_tribe: 1 }, intensity: 3 },
  },
  {
    jurisdiction: "USA",
    regime: "Civil War/Reconstruction",
    startYear: 1861,
    endYear: 1876,
    description:
      "The Union fought to end secession and slavery, followed by radical Reconstruction that briefly expanded Black citizenship before collapsing under Southern resistance.",
    MAT: 3, CD: 3, CU: 3, MOR: 4,
    PRO: 3, COM: 2,
    ZS: 5, ONT_H: 3, ONT_S: 5,
    PF: 5, TRB: 4, ENG: 5,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.16, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.34, gender: 0.09, political_tribe: 1 }, intensity: 3 },
  },
  {
    jurisdiction: "USA",
    regime: "Gilded Age",
    startYear: 1877,
    endYear: 1895,
    description:
      "Laissez-faire capitalism and industrial barons dominated while Jim Crow disenfranchised Black Americans and labor unrest grew.",
    MAT: 5, CD: 4, CU: 2, MOR: 2,
    PRO: 3, COM: 3,
    ZS: 4, ONT_H: 3, ONT_S: 2,
    PF: 4, TRB: 4, ENG: 3,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.16, religious: 0.41, class: 0.05, ideological: 0.34, gender: 0.09, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "USA",
    regime: "Progressive Era",
    startYear: 1896,
    endYear: 1919,
    description:
      "Theodore Roosevelt and Woodrow Wilson advanced antitrust regulation, women's suffrage, and international engagement through World War I.",
    MAT: 3, CD: 3, CU: 3, MOR: 4,
    PRO: 4, COM: 3,
    ZS: 3, ONT_H: 4, ONT_S: 4,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 5,
    morBoundaries: { boundaries: { national: 0.12, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "USA",
    regime: "Roaring Twenties/Normalcy",
    startYear: 1920,
    endYear: 1932,
    description:
      "Harding and Coolidge restored laissez-faire normalcy amid cultural upheaval, Prohibition, and a speculative boom that ended in the Great Depression.",
    MAT: 5, CD: 4, CU: 2, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 2,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.38, ethnic_racial: 0.05, religious: 0.29, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "USA",
    regime: "New Deal/WWII",
    startYear: 1933,
    endYear: 1952,
    description:
      "FDR built the modern welfare state and led the arsenal of democracy through World War II, with Truman managing the early Cold War and desegregating the military.",
    MAT: 2, CD: 3, CU: 3, MOR: 4,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 4, ONT_S: 4,
    PF: 4, TRB: 3, ENG: 5,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.12, ethnic_racial: 0.05, religious: 0.05, class: 0.29, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "USA",
    regime: "Cold War Consensus",
    startYear: 1953,
    endYear: 1968,
    description:
      "Bipartisan containment policy under Eisenhower and JFK gave way to LBJ's Great Society and deepening Vietnam involvement.",
    MAT: 3, CD: 3, CU: 3, MOR: 4,
    PRO: 4, COM: 4,
    ZS: 3, ONT_H: 4, ONT_S: 4,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.12, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "USA",
    regime: "Crisis/Realignment",
    startYear: 1969,
    endYear: 1980,
    description:
      "Nixon's imperial presidency and Watergate scandal eroded institutional trust, while stagflation and the Carter malaise undermined economic confidence.",
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 4, ONT_H: 2, ONT_S: 4,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 3,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "USA",
    regime: "Reagan-Clinton",
    startYear: 1981,
    endYear: 2007,
    description:
      "The conservative revolution and Third Way centrism defined a unipolar era of deregulation, globalization, and American hegemony.",
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 4, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 2,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "USA",
    regime: "Polarization Era",
    startYear: 2008,
    endYear: 2026,
    description:
      "The financial crisis, Obama and Trump presidencies, and social media-driven hyperpolarization fractured the political consensus and eroded institutional trust.",
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 1,
    ZS: 4, ONT_H: 2, ONT_S: 4,
    PF: 5, TRB: 4, ENG: 5,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 0.23, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.48, gender: 0.09, political_tribe: 1 }, intensity: 3 },
  },

  // ──────────────────────────────────────────────
  // 2. MEXICO
  // ──────────────────────────────────────────────
  {
    jurisdiction: "Mexico",
    regime: "Bourbon Viceroyalty of New Spain",
    startYear: 1776,
    endYear: 1788,
    description:
      "The Viceroyalty of New Spain under Bourbon Reforms (intendancy system from 1786, freer intra-imperial trade from 1778, expulsion of Jesuits 1767) generated significant silver revenue while maintaining the sistema de castas racial-legal hierarchy and Catholic confessional state.",
    MAT: 4, CD: 5, CU: 2, MOR: 1,
    PRO: 3, COM: 2,
    ZS: 4, ONT_H: 3, ONT_S: 3,
    PF: 2, TRB: 4, ENG: 2,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.62, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.16, political_tribe: 0.25 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "Late Colonial/Independence",
    startYear: 1789,
    endYear: 1821,
    description:
      "Bourbon reforms stoked colonial resentment, sparking the independence movements of Hidalgo and Morelos against Spanish rule.",
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 3, ONT_S: 5,
    PF: 3, TRB: 4, ENG: 4,
    EPS: 2, AES: 4,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.05, religious: 0.69, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "First Empire/Early Republic",
    startYear: 1822,
    endYear: 1854,
    description:
      "Iturbide's brief empire gave way to chronic instability under Santa Anna, with Mexico losing half its territory to the United States.",
    MAT: 4, CD: 4, CU: 2, MOR: 2,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 2, ONT_S: 4,
    PF: 3, TRB: 4, ENG: 4,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.16, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "La Reforma",
    startYear: 1855,
    endYear: 1876,
    description:
      "Benito Juarez enacted liberal Reform Laws separating Church and state, then led resistance against French-imposed Emperor Maximilian.",
    MAT: 3, CD: 2, CU: 3, MOR: 4,
    PRO: 3, COM: 2,
    ZS: 4, ONT_H: 4, ONT_S: 5,
    PF: 4, TRB: 3, ENG: 5,
    EPS: 0, AES: 5,
    morBoundaries: { boundaries: { national: 0.12, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "Porfiriato",
    startYear: 1877,
    endYear: 1910,
    description:
      "Porfirio Diaz's long dictatorship modernized infrastructure and attracted foreign investment while deepening inequality and suppressing dissent.",
    MAT: 5, CD: 4, CU: 4, MOR: 2,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 2, ONT_S: 2,
    PF: 1, TRB: 4, ENG: 3,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.05, religious: 0.26, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "Revolution",
    startYear: 1911,
    endYear: 1920,
    description:
      "A decade of revolutionary upheaval pitted Madero, Zapata, Villa, and Carranza against each other and the old order, killing over a million people.",
    MAT: 1, CD: 3, CU: 3, MOR: 3,
    PRO: 1, COM: 1,
    ZS: 5, ONT_H: 4, ONT_S: 5,
    PF: 4, TRB: 4, ENG: 5,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 0.23, ethnic_racial: 0.05, religious: 0.05, class: 0.55, ideological: 0.48, gender: 0.09, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "Revolutionary State",
    startYear: 1921,
    endYear: 1940,
    description:
      "The post-revolutionary state consolidated under Calles and Cardenas, who nationalized oil and distributed land to peasants.",
    MAT: 2, CD: 3, CU: 3, MOR: 3,
    PRO: 2, COM: 2,
    ZS: 3, ONT_H: 4, ONT_S: 3,
    PF: 1, TRB: 4, ENG: 4,
    EPS: 3, AES: 5,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.41, ideological: 0.12, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "PRI Hegemony/Miracle",
    startYear: 1941,
    endYear: 1968,
    description:
      "Single-party PRI rule delivered sustained economic growth and political stability through corporatist control and import substitution industrialization.",
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 2,
    PF: 1, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.05, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "PRI Crisis",
    startYear: 1969,
    endYear: 1988,
    description:
      "The 1968 Tlatelolco massacre shattered the regime's legitimacy, followed by oil boom-and-bust cycles and the devastating 1982 debt crisis.",
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 2, ONT_S: 4,
    PF: 1, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.05, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "Democratization",
    startYear: 1989,
    endYear: 2012,
    description:
      "NAFTA integration and PAN's 2000 election victory ended one-party rule, but the drug war escalated into a major security crisis.",
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Mexico",
    regime: "AMLO/Morena",
    startYear: 2013,
    endYear: 2026,
    description:
      "Lopez Obrador's 'Fourth Transformation' brought populist left governance with centralized power, austerity for institutions, and expanded social transfers.",
    MAT: 2, CD: 3, CU: 3, MOR: 3,
    PRO: 2, COM: 1,
    ZS: 3, ONT_H: 3, ONT_S: 4,
    PF: 4, TRB: 4, ENG: 5,
    EPS: 3, AES: 3,
    morBoundaries: { boundaries: { national: 0.23, ethnic_racial: 0.05, religious: 0.05, class: 0.41, ideological: 0.48, gender: 0.09, political_tribe: 0.75 }, intensity: 2.25 },
  },

  // ──────────────────────────────────────────────
  // 3. BRAZIL
  // ──────────────────────────────────────────────
  {
    jurisdiction: "Brazil",
    regime: "Late Pombaline Brazil",
    startYear: 1776,
    endYear: 1788,
    description:
      "Portuguese Brazil after the dismissal of Pombal (1777) saw the slave-based plantation and gold-mining economy continue, with the Inconfidência Mineira (1789) brewing among Minas Gerais elites resentful of Portuguese taxation. Capital remained at Rio de Janeiro (moved from Salvador 1763).",
    MAT: 4, CD: 5, CU: 2, MOR: 1,
    PRO: 3, COM: 2,
    ZS: 4, ONT_H: 3, ONT_S: 3,
    PF: 2, TRB: 4, ENG: 2,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.62, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.16, political_tribe: 0.25 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Brazil",
    regime: "Colonial/Portuguese Court",
    startYear: 1789,
    endYear: 1821,
    description:
      "The Inconfidencia Mineira failed to spark independence, but the Portuguese court's flight to Rio de Janeiro in 1808 transformed Brazil into the seat of empire.",
    MAT: 5, CD: 5, CU: 2, MOR: 2,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 2, ONT_S: 2,
    PF: 1, TRB: 4, ENG: 2,
    EPS: 2, AES: 0,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.41, religious: 0.69, class: 0.05, ideological: 0.23, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Brazil",
    regime: "Empire",
    startYear: 1822,
    endYear: 1889,
    description:
      "Pedro I declared independence and Pedro II presided over a stable constitutional monarchy sustained by slave labor until abolition in 1888 precipitated the republic.",
    MAT: 5, CD: 4, CU: 3, MOR: 2,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 2,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.05, religious: 0.26, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Brazil",
    regime: "Old Republic",
    startYear: 1889,
    endYear: 1930,
    description:
      "Coffee oligarchs from Sao Paulo and Minas Gerais rotated power through coronelismo and fraudulent elections in a decentralized federal system.",
    MAT: 5, CD: 4, CU: 2, MOR: 2,
    PRO: 3, COM: 3,
    ZS: 4, ONT_H: 2, ONT_S: 2,
    PF: 3, TRB: 4, ENG: 2,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.16, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Brazil",
    regime: "Vargas Era",
    startYear: 1930,
    endYear: 1945,
    description:
      "Getulio Vargas seized power, established the Estado Novo corporatist dictatorship, and launched state-led industrialization with labor co-optation.",
    MAT: 2, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 1,
    ZS: 3, ONT_H: 3, ONT_S: 4,
    PF: 1, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.05, religious: 0.41, class: 0.41, ideological: 0.26, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Brazil",
    regime: "Democratic Experiment",
    startYear: 1946,
    endYear: 1963,
    description:
      "Competitive democracy returned with populist leaders and Juscelino Kubitschek's ambitious modernization program that built Brasilia as the new capital.",
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 4, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 5,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Brazil",
    regime: "Military Dictatorship",
    startYear: 1964,
    endYear: 1984,
    description:
      "Military generals ruled through repression and the economic 'miracle' of high growth, but left a legacy of inequality, debt, and human rights abuses.",
    MAT: 4, CD: 4, CU: 4, MOR: 2,
    PRO: 2, COM: 1,
    ZS: 4, ONT_H: 1, ONT_S: 3,
    PF: 1, TRB: 4, ENG: 3,
    EPS: 1, AES: 1,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.05, religious: 0.26, class: 0.05, ideological: 0.26, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Brazil",
    regime: "Redemocratization",
    startYear: 1985,
    endYear: 2002,
    description:
      "The New Republic brought a progressive 1988 constitution, and Fernando Henrique Cardoso's Real Plan finally tamed hyperinflation.",
    MAT: 3, CD: 2, CU: 4, MOR: 4,
    PRO: 4, COM: 4,
    ZS: 3, ONT_H: 4, ONT_S: 3,
    PF: 4, TRB: 2, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.09, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.15, gender: 0.06, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Brazil",
    regime: "Lula/PT Era",
    startYear: 2003,
    endYear: 2015,
    description:
      "Lula's Workers' Party expanded social programs like Bolsa Familia during a commodity boom, but the era ended in massive corruption scandals.",
    MAT: 2, CD: 2, CU: 4, MOR: 4,
    PRO: 3, COM: 3,
    ZS: 2, ONT_H: 4, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 3,
    morBoundaries: { boundaries: { national: 0.12, ethnic_racial: 0.05, religious: 0.05, class: 0.34, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Brazil",
    regime: "Bolsonaro/Crisis",
    startYear: 2016,
    endYear: 2026,
    description:
      "Dilma's impeachment opened the door to Bolsonaro's far-right populism, deepening polarization amid institutional crisis and pandemic mismanagement.",
    MAT: 4, CD: 5, CU: 2, MOR: 2,
    PRO: 2, COM: 1,
    ZS: 4, ONT_H: 1, ONT_S: 4,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 1, ethnic_racial: 0.53, religious: 0.53, class: 0.05, ideological: 0.62, gender: 0.1, political_tribe: 1 }, intensity: 3 },
  },

  // ──────────────────────────────────────────────
  // 4. ARGENTINA
  // ──────────────────────────────────────────────
  {
    jurisdiction: "Argentina",
    regime: "Viceroyalty of Río de la Plata",
    startYear: 1776,
    endYear: 1788,
    description:
      "The Viceroyalty of Río de la Plata was created in 1776 with Buenos Aires as the new capital, splitting Upper Peru (silver) from the Peruvian viceroyalty and giving the southern Atlantic its own administrative center. Free intra-imperial trade (1778) and intendancy reform (1782) restructured commerce.",
    MAT: 4, CD: 4, CU: 3, MOR: 2,
    PRO: 3, COM: 2,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 2, TRB: 3, ENG: 2,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.38, ethnic_racial: 0.05, religious: 0.19, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.25 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Argentina",
    regime: "Independence/Rivadavia",
    startYear: 1810,
    endYear: 1829,
    description:
      "The May Revolution launched Argentine independence, and Rivadavia's short-lived presidency attempted liberal reforms from Buenos Aires.",
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 4, ONT_S: 4,
    PF: 3, TRB: 3, ENG: 4,
    EPS: 0, AES: 5,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Argentina",
    regime: "Rosas",
    startYear: 1830,
    endYear: 1852,
    description:
      "Juan Manuel de Rosas imposed caudillo rule over Buenos Aires with terror and populist federalism, dominating the confederation until his overthrow at Caseros.",
    MAT: 4, CD: 5, CU: 4, MOR: 2,
    PRO: 1, COM: 1,
    ZS: 5, ONT_H: 1, ONT_S: 3,
    PF: 1, TRB: 5, ENG: 4,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 0.72, ethnic_racial: 0.38, religious: 0.34, class: 0.05, ideological: 0.34, gender: 0.1, political_tribe: 0 }, intensity: 3 },
  },
  {
    jurisdiction: "Argentina",
    regime: "Liberal Republic",
    startYear: 1853,
    endYear: 1915,
    description:
      "The 1853 constitution ushered in an export-led boom fueled by European immigration, making Argentina one of the world's wealthiest nations.",
    MAT: 5, CD: 3, CU: 4, MOR: 3,
    PRO: 4, COM: 3,
    ZS: 2, ONT_H: 4, ONT_S: 2,
    PF: 3, TRB: 2, ENG: 3,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.07, gender: 0.06, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Argentina",
    regime: "Radical/Conservative",
    startYear: 1916,
    endYear: 1942,
    description:
      "Yrigoyen's Radical Party brought middle-class democracy, interrupted by the 1930 coup that began the 'Infamous Decade' of conservative fraud.",
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Argentina",
    regime: "Peronist Era",
    startYear: 1943,
    endYear: 1955,
    description:
      "Juan Peron and Eva Peron built justicialismo on organized labor, nationalist industrialization, and mass political mobilization.",
    MAT: 2, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 1,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 0.95, ethnic_racial: 0.05, religious: 0.53, class: 0.53, ideological: 0.62, gender: 0.1, political_tribe: 1 }, intensity: 3 },
  },
  {
    jurisdiction: "Argentina",
    regime: "Instability/Coups",
    startYear: 1956,
    endYear: 1972,
    description:
      "A cycle of military coups and weak civilian governments under Aramburu, Frondizi, and Ongania failed to resolve the Peronist question.",
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 1, ONT_S: 4,
    PF: 3, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.05, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Argentina",
    regime: "Dirty War",
    startYear: 1973,
    endYear: 1983,
    description:
      "Peron's chaotic return and death gave way to a military junta that waged a 'dirty war' of disappearances, ending with the Falklands defeat.",
    MAT: 4, CD: 5, CU: 5, MOR: 1,
    PRO: 1, COM: 1,
    ZS: 5, ONT_H: 1, ONT_S: 5,
    PF: 1, TRB: 5, ENG: 4,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.72, ethnic_racial: 0.67, religious: 0.34, class: 0.05, ideological: 0.34, gender: 0.19, political_tribe: 0 }, intensity: 3 },
  },
  {
    jurisdiction: "Argentina",
    regime: "Democratic Restoration",
    startYear: 1984,
    endYear: 2001,
    description:
      "Alfonsin restored democracy and tried the junta, while Menem's neoliberal reforms privatized the economy before the 2001 financial collapse.",
    MAT: 4, CD: 2, CU: 3, MOR: 4,
    PRO: 4, COM: 4,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 2, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.09, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.15, gender: 0.06, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Argentina",
    regime: "Kirchnerismo/Crisis",
    startYear: 2002,
    endYear: 2026,
    description:
      "Nestor and Cristina Kirchner rebuilt Peronist populism after the 2001 crisis, eventually giving way to Milei's libertarian disruption.",
    MAT: 2, CD: 3, CU: 3, MOR: 3,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 3, ONT_S: 4,
    PF: 5, TRB: 4, ENG: 5,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 0.23, ethnic_racial: 0.05, religious: 0.05, class: 0.41, ideological: 0.34, gender: 0.09, political_tribe: 1 }, intensity: 3 },
  },

  // ──────────────────────────────────────────────
  // 5. CANADA
  // ──────────────────────────────────────────────
  {
    jurisdiction: "Canada",
    regime: "British North America (Quebec Act era)",
    startYear: 1776,
    endYear: 1788,
    description:
      "British North America was reorganized by the Quebec Act (1774) and the loss of the Thirteen Colonies; Loyalist refugees from the United States resettled Nova Scotia, New Brunswick (created 1784), and Upper Canada. French Catholic civil law was preserved in Quebec while British common law and Protestant officialdom dominated elsewhere.",
    MAT: 4, CD: 4, CU: 2, MOR: 2,
    PRO: 4, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 2, TRB: 3, ENG: 2,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.53, ethnic_racial: 0.12, religious: 0.29, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.25 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Canada",
    regime: "British North America",
    startYear: 1789,
    endYear: 1866,
    description:
      "Upper and Lower Canada navigated rebellions and the Durham Report before achieving responsible government within the British imperial framework.",
    MAT: 4, CD: 4, CU: 3, MOR: 3,
    PRO: 4, COM: 4,
    ZS: 3, ONT_H: 3, ONT_S: 2,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.24, ethnic_racial: 0.05, religious: 0.19, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Canada",
    regime: "Confederation/Macdonald",
    startYear: 1867,
    endYear: 1895,
    description:
      "Confederation united the provinces under Macdonald's National Policy of tariffs, railways, and western settlement, including the residential school system.",
    MAT: 4, CD: 4, CU: 2, MOR: 2,
    PRO: 4, COM: 4,
    ZS: 3, ONT_H: 3, ONT_S: 2,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.53, ethnic_racial: 0.12, religious: 0.29, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Canada",
    regime: "Laurier/Early 20th",
    startYear: 1896,
    endYear: 1929,
    description:
      "Wilfrid Laurier presided over a massive immigration boom, while World War I's conscription crisis deepened the English-French divide.",
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 4, COM: 4,
    ZS: 3, ONT_H: 3, ONT_S: 2,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Canada",
    regime: "Depression/War/Postwar",
    startYear: 1930,
    endYear: 1956,
    description:
      "The Depression spawned prairie populism and social credit, while World War II and postwar prosperity expanded the federal welfare state.",
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 4, COM: 4,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Canada",
    regime: "Quiet Revolution/Trudeau Sr.",
    startYear: 1957,
    endYear: 1983,
    description:
      "Quebec's Quiet Revolution modernized French Canada, and Pierre Trudeau entrenched bilingualism, multiculturalism, and the Charter of Rights and Freedoms.",
    MAT: 2, CD: 2, CU: 5, MOR: 5,
    PRO: 5, COM: 4,
    ZS: 2, ONT_H: 4, ONT_S: 4,
    PF: 4, TRB: 2, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.09, ethnic_racial: 0.05, religious: 0.05, class: 0.19, ideological: 0.15, gender: 0.06, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Canada",
    regime: "Mulroney/Chretien",
    startYear: 1984,
    endYear: 2005,
    description:
      "Mulroney pursued free trade and constitutional reform, Chretien eliminated the deficit, and two Quebec sovereignty referendums tested national unity.",
    MAT: 4, CD: 2, CU: 4, MOR: 4,
    PRO: 5, COM: 4,
    ZS: 2, ONT_H: 3, ONT_S: 4,
    PF: 4, TRB: 2, ENG: 3,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.09, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.15, gender: 0.06, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Canada",
    regime: "Modern Canada",
    startYear: 2006,
    endYear: 2026,
    description:
      "Harper's Conservatives gave way to Justin Trudeau's progressive agenda, as Indigenous reconciliation and a housing affordability crisis dominate national debate.",
    MAT: 3, CD: 2, CU: 5, MOR: 4,
    PRO: 4, COM: 4,
    ZS: 2, ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 2, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.09, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.15, gender: 0.06, political_tribe: 0.75 }, intensity: 2.25 },
  },

  // ──────────────────────────────────────────────
  // 6. COLOMBIA
  // ──────────────────────────────────────────────
  {
    jurisdiction: "Colombia",
    regime: "Viceroyalty of New Granada",
    startYear: 1776,
    endYear: 1788,
    description:
      "The Viceroyalty of New Granada (re-established 1739) governed Colombia, Venezuela, Ecuador, and Panama; the Comuneros Revolt (1781) at Socorro was contained through negotiation under Archbishop-Viceroy Caballero y Góngora. Bourbon administrative reforms and trade liberalization defined the period.",
    MAT: 4, CD: 5, CU: 3, MOR: 1,
    PRO: 3, COM: 2,
    ZS: 4, ONT_H: 3, ONT_S: 3,
    PF: 2, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.51, religious: 0.26, class: 0.05, ideological: 0.12, gender: 0.16, political_tribe: 0.25 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Colombia",
    regime: "Gran Colombia/Independence",
    startYear: 1810,
    endYear: 1830,
    description:
      "Bolivar liberated New Granada and forged Gran Colombia, but regional rivalries dissolved the union within two decades.",
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 2,
    ZS: 4, ONT_H: 4, ONT_S: 4,
    PF: 3, TRB: 3, ENG: 4,
    EPS: 0, AES: 5,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Colombia",
    regime: "Conservative Hegemony",
    startYear: 1831,
    endYear: 1885,
    description:
      "Recurring civil wars between Liberals and Conservatives defined the era, with the Church playing a central role in Conservative governance.",
    MAT: 5, CD: 5, CU: 2, MOR: 2,
    PRO: 3, COM: 2,
    ZS: 4, ONT_H: 2, ONT_S: 3,
    PF: 4, TRB: 4, ENG: 4,
    EPS: 2, AES: 4,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.41, religious: 0.69, class: 0.05, ideological: 0.44, gender: 0.09, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Colombia",
    regime: "Regeneration/Thousand Days",
    startYear: 1886,
    endYear: 1929,
    description:
      "The Regeneration centralized power under a new constitution, the devastating Thousand Days' War killed over 100,000, and Panama seceded with US backing.",
    MAT: 5, CD: 5, CU: 4, MOR: 2,
    PRO: 3, COM: 2,
    ZS: 4, ONT_H: 2, ONT_S: 3,
    PF: 4, TRB: 4, ENG: 3,
    EPS: 2, AES: 0,
    morBoundaries: { boundaries: { national: 0.73, ethnic_racial: 0.3, religious: 0.55, class: 0.05, ideological: 0.44, gender: 0.09, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Colombia",
    regime: "Liberal Republic/La Violencia",
    startYear: 1930,
    endYear: 1957,
    description:
      "Liberal reforms gave way to La Violencia, a brutal partisan civil war killing 200,000, ended only by military dictatorship.",
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 1,
    ZS: 5, ONT_H: 2, ONT_S: 5,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 0.95, ethnic_racial: 0.05, religious: 0.53, class: 0.05, ideological: 0.62, gender: 0.1, political_tribe: 1 }, intensity: 3 },
  },
  {
    jurisdiction: "Colombia",
    regime: "National Front",
    startYear: 1958,
    endYear: 1973,
    description:
      "Liberals and Conservatives agreed to alternate power, restoring elite stability but excluding the left and enabling FARC's emergence.",
    MAT: 4, CD: 4, CU: 2, MOR: 3,
    PRO: 4, COM: 5,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 5, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.73, ethnic_racial: 0.05, religious: 0.41, class: 0.05, ideological: 0.34, gender: 0.09, political_tribe: 1 }, intensity: 3 },
  },
  {
    jurisdiction: "Colombia",
    regime: "Drug War/Constitution",
    startYear: 1974,
    endYear: 2002,
    description:
      "The Medellin and Cali cartels unleashed narco-violence, prompting the progressive 1991 constitution amid ongoing guerrilla and paramilitary conflict.",
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 4, ONT_H: 2, ONT_S: 4,
    PF: 4, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.23, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.34, gender: 0.09, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Colombia",
    regime: "Uribe/Santos/Peace",
    startYear: 2003,
    endYear: 2026,
    description:
      "Uribe's security-first approach weakened FARC, Santos signed a historic peace deal, and Petro became the first leftist president.",
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },

  // ──────────────────────────────────────────────
  // 7. CHILE
  // ──────────────────────────────────────────────
  {
    jurisdiction: "Chile",
    regime: "Independence/O'Higgins",
    startYear: 1810,
    endYear: 1830,
    description:
      "Bernardo O'Higgins led Chile's liberation from Spain and established an autocratic republic before being forced into exile.",
    MAT: 4, CD: 3, CU: 2, MOR: 3,
    PRO: 3, COM: 2,
    ZS: 3, ONT_H: 3, ONT_S: 4,
    PF: 3, TRB: 3, ENG: 4,
    EPS: 0, AES: 5,
    morBoundaries: { boundaries: { national: 0.19, ethnic_racial: 0.05, religious: 0.15, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Chile",
    regime: "Conservative Republic",
    startYear: 1831,
    endYear: 1860,
    description:
      "Diego Portales designed a centralized authoritarian constitution that delivered exceptional stability and fueled mining-driven economic growth.",
    MAT: 5, CD: 5, CU: 4, MOR: 2,
    PRO: 4, COM: 2,
    ZS: 3, ONT_H: 2, ONT_S: 1,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.3, religious: 0.26, class: 0.05, ideological: 0.23, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Chile",
    regime: "Liberal Republic",
    startYear: 1861,
    endYear: 1924,
    description:
      "Parliamentary politics and the War of the Pacific secured nitrate-rich territories, driving export wealth and liberal institutional development.",
    MAT: 5, CD: 3, CU: 3, MOR: 3,
    PRO: 4, COM: 4,
    ZS: 3, ONT_H: 3, ONT_S: 2,
    PF: 4, TRB: 3, ENG: 3,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Chile",
    regime: "Social Question",
    startYear: 1925,
    endYear: 1958,
    description:
      "A new constitution, Ibanez's interventionism, and Popular Front coalitions addressed growing labor demands and social inequality.",
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Chile",
    regime: "Christian Democracy/Left",
    startYear: 1959,
    endYear: 1972,
    description:
      "Eduardo Frei's 'Revolution in Liberty' was overtaken by Salvador Allende's democratic socialist experiment under Unidad Popular.",
    MAT: 1, CD: 2, CU: 4, MOR: 4,
    PRO: 3, COM: 2,
    ZS: 3, ONT_H: 5, ONT_S: 4,
    PF: 5, TRB: 3, ENG: 5,
    EPS: 0, AES: 5,
    morBoundaries: { boundaries: { national: 0.12, ethnic_racial: 0.05, religious: 0.05, class: 0.34, ideological: 0.24, gender: 0.07, political_tribe: 1 }, intensity: 3 },
  },
  {
    jurisdiction: "Chile",
    regime: "Pinochet",
    startYear: 1973,
    endYear: 1989,
    description:
      "Augusto Pinochet's military dictatorship crushed the left through systematic repression while Chicago Boys economists imposed radical free-market reforms.",
    MAT: 5, CD: 5, CU: 5, MOR: 1,
    PRO: 1, COM: 1,
    ZS: 5, ONT_H: 1, ONT_S: 3,
    PF: 1, TRB: 4, ENG: 3,
    EPS: 0, AES: 4,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.51, religious: 0.26, class: 0.05, ideological: 0.37, gender: 0.16, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Chile",
    regime: "Concertacion",
    startYear: 1990,
    endYear: 2009,
    description:
      "The center-left Concertacion coalition managed a model democratic transition, maintaining market economics while building consensus and a copper stabilization fund.",
    MAT: 3, CD: 2, CU: 4, MOR: 4,
    PRO: 5, COM: 5,
    ZS: 2, ONT_H: 4, ONT_S: 2,
    PF: 4, TRB: 2, ENG: 4,
    EPS: 0, AES: 0,
    morBoundaries: { boundaries: { national: 0.09, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.15, gender: 0.06, political_tribe: 0.75 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Chile",
    regime: "Estallido/Boric",
    startYear: 2010,
    endYear: 2026,
    description:
      "Mass protests against inequality in 2019 launched a constitutional rewrite process, and Gabriel Boric's young left government sought transformative reform.",
    MAT: 2, CD: 2, CU: 4, MOR: 4,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 3, ONT_S: 4,
    PF: 4, TRB: 3, ENG: 5,
    EPS: 0, AES: 5,
    morBoundaries: { boundaries: { national: 0.12, ethnic_racial: 0.05, religious: 0.05, class: 0.34, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },

  // ──────────────────────────────────────────────
  // 8. CUBA
  // ──────────────────────────────────────────────
  {
    jurisdiction: "Cuba",
    regime: "Spanish Colony",
    startYear: 1789,
    endYear: 1897,
    description:
      "Cuba remained Spain's prized sugar colony sustained by African slavery, with periodic independence movements brutally suppressed.",
    MAT: 5, CD: 5, CU: 5, MOR: 1,
    PRO: 2, COM: 1,
    ZS: 5, ONT_H: 1, ONT_S: 3,
    PF: 2, TRB: 5, ENG: 3,
    EPS: 2, AES: 0,
    morBoundaries: { boundaries: { national: 0.72, ethnic_racial: 0.67, religious: 0.72, class: 0.05, ideological: 0.48, gender: 0.19, political_tribe: 0.25 }, intensity: 3 },
  },
  {
    jurisdiction: "Cuba",
    regime: "US Intervention/Platt",
    startYear: 1898,
    endYear: 1932,
    description:
      "The Spanish-American War brought nominal independence under the Platt Amendment, making Cuba a US protectorate dependent on sugar exports.",
    MAT: 5, CD: 4, CU: 2, MOR: 2,
    PRO: 3, COM: 3,
    ZS: 4, ONT_H: 2, ONT_S: 3,
    PF: 3, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.53, ethnic_racial: 0.12, religious: 0.29, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Cuba",
    regime: "Batista/Republic",
    startYear: 1933,
    endYear: 1958,
    description:
      "Batista dominated Cuban politics through coups and elections, presiding over Havana's modernization and Mafia-linked corruption before Castro's revolution.",
    MAT: 5, CD: 4, CU: 2, MOR: 2,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 2, ONT_S: 3,
    PF: 2, TRB: 3, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.53, ethnic_racial: 0.12, religious: 0.29, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.25 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Cuba",
    regime: "Revolutionary Cuba",
    startYear: 1959,
    endYear: 1975,
    description:
      "Fidel Castro's revolution nationalized the economy and aligned with the Soviet Union, surviving the Bay of Pigs invasion and the Missile Crisis.",
    MAT: 1, CD: 2, CU: 2, MOR: 4,
    PRO: 1, COM: 1,
    ZS: 4, ONT_H: 5, ONT_S: 5,
    PF: 1, TRB: 4, ENG: 5,
    EPS: 4, AES: 5,
    morBoundaries: { boundaries: { national: 0.19, ethnic_racial: 0.05, religious: 0.19, class: 0.62, ideological: 0.26, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Cuba",
    regime: "Late Castro/Special Period",
    startYear: 1976,
    endYear: 2006,
    description:
      "Institutionalized socialism faced catastrophic economic crisis when Soviet support collapsed, forcing limited market experiments during the Special Period.",
    MAT: 1, CD: 3, CU: 4, MOR: 3,
    PRO: 2, COM: 1,
    ZS: 4, ONT_H: 3, ONT_S: 3,
    PF: 1, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.55, ideological: 0.26, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Cuba",
    regime: "Post-Castro",
    startYear: 2007,
    endYear: 2026,
    description:
      "Raul Castro and Diaz-Canel introduced limited economic reforms while maintaining one-party control amid growing emigration and social discontent.",
    MAT: 2, CD: 3, CU: 2, MOR: 3,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 2, ONT_S: 3,
    PF: 1, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.26, ethnic_racial: 0.05, religious: 0.19, class: 0.41, ideological: 0.12, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },

  // ──────────────────────────────────────────────
  // 9. PERU
  // ──────────────────────────────────────────────
  {
    jurisdiction: "Peru",
    regime: "Viceroyalty of Peru after Túpac Amaru II",
    startYear: 1776,
    endYear: 1788,
    description:
      "The Viceroyalty of Peru lost the Río de la Plata territories (transferred to a new viceroyalty in 1776) and faced the massive Túpac Amaru II indigenous-mestizo rebellion (1780–83), the largest anti-colonial uprising in Spanish America before independence. Bourbon reforms (intendancies 1784) imposed extractive reorganization.",
    MAT: 4, CD: 5, CU: 2, MOR: 1,
    PRO: 3, COM: 2,
    ZS: 5, ONT_H: 3, ONT_S: 3,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.62, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.16, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Peru",
    regime: "Colonial/Independence",
    startYear: 1789,
    endYear: 1824,
    description:
      "Peru was Spain's most important South American viceroyalty; Tupac Amaru's rebellion and Bolivar's campaigns finally ended colonial rule.",
    MAT: 5, CD: 5, CU: 4, MOR: 1,
    PRO: 2, COM: 1,
    ZS: 5, ONT_H: 2, ONT_S: 4,
    PF: 2, TRB: 5, ENG: 3,
    EPS: 2, AES: 0,
    morBoundaries: { boundaries: { national: 0.72, ethnic_racial: 0.67, religious: 0.72, class: 0.05, ideological: 0.48, gender: 0.19, political_tribe: 0.25 }, intensity: 3 },
  },
  {
    jurisdiction: "Peru",
    regime: "Caudillo Era",
    startYear: 1825,
    endYear: 1878,
    description:
      "Military strongmen competed for power during the guano boom, which briefly enriched the state before the disastrous War of the Pacific.",
    MAT: 5, CD: 4, CU: 2, MOR: 2,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 2, ONT_S: 3,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.16, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Peru",
    regime: "Aristocratic Republic",
    startYear: 1879,
    endYear: 1919,
    description:
      "After defeat in the War of the Pacific, a coastal oligarchy rebuilt the state through the Civilista Party and export-oriented growth.",
    MAT: 5, CD: 4, CU: 2, MOR: 2,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 2, ONT_S: 2,
    PF: 3, TRB: 4, ENG: 3,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.16, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Peru",
    regime: "Leguia/APRA",
    startYear: 1920,
    endYear: 1967,
    description:
      "Leguia's modernizing autocracy gave way to military-civilian oscillation, with APRA's populist movement repeatedly blocked from power.",
    MAT: 3, CD: 4, CU: 2, MOR: 3,
    PRO: 2, COM: 2,
    ZS: 3, ONT_H: 3, ONT_S: 3,
    PF: 3, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.55, ethnic_racial: 0.05, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Peru",
    regime: "Velasco/Military",
    startYear: 1968,
    endYear: 1979,
    description:
      "General Velasco's left-wing military government nationalized industries and enacted sweeping agrarian reform to dismantle the oligarchy.",
    MAT: 1, CD: 3, CU: 3, MOR: 3,
    PRO: 2, COM: 1,
    ZS: 3, ONT_H: 3, ONT_S: 4,
    PF: 1, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.41, ideological: 0.26, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Peru",
    regime: "Democracy/Fujimori",
    startYear: 1980,
    endYear: 2000,
    description:
      "Democracy returned amid Sendero Luminoso's Maoist insurgency; Fujimori's autogolpe crushed the guerrillas but installed authoritarian neoliberalism.",
    MAT: 4, CD: 3, CU: 2, MOR: 3,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 1, ONT_S: 4,
    PF: 3, TRB: 4, ENG: 4,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.26, ethnic_racial: 0.05, religious: 0.19, class: 0.05, ideological: 0.12, gender: 0.09, political_tribe: 0.5 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Peru",
    regime: "Post-Fujimori",
    startYear: 2001,
    endYear: 2026,
    description:
      "Chronic presidential instability and Pedro Castillo's chaotic tenure deepened institutional crisis in one of Latin America's most fragile democracies.",
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 3, ONT_H: 2, ONT_S: 4,
    PF: 4, TRB: 3, ENG: 4,
    EPS: 3, AES: 3,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 0.75 }, intensity: 2.25 },
  },

  // ──────────────────────────────────────────────
  // 10. VENEZUELA
  // ──────────────────────────────────────────────
  {
    jurisdiction: "Venezuela",
    regime: "Captaincy General of Venezuela",
    startYear: 1776,
    endYear: 1788,
    description:
      "The Captaincy General of Venezuela was created in 1777 as a separate jurisdiction (under New Granada nominally) governed from Caracas, with cacao plantation slavery and intra-elite mantuano (white creole) politics defining the social order. Real Audiencia of Caracas established 1786.",
    MAT: 4, CD: 5, CU: 2, MOR: 1,
    PRO: 3, COM: 2,
    ZS: 4, ONT_H: 3, ONT_S: 3,
    PF: 2, TRB: 4, ENG: 2,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.62, religious: 0.41, class: 0.05, ideological: 0.12, gender: 0.16, political_tribe: 0.25 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Venezuela",
    regime: "Independence/Gran Colombia",
    startYear: 1810,
    endYear: 1830,
    description:
      "Venezuela was the birthplace of Bolivar's independence movement and Gran Colombia, but internal divisions soon tore the federation apart.",
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 2, COM: 2,
    ZS: 4, ONT_H: 4, ONT_S: 4,
    PF: 3, TRB: 3, ENG: 4,
    EPS: 0, AES: 5,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Venezuela",
    regime: "Caudillo Era",
    startYear: 1831,
    endYear: 1908,
    description:
      "From Paez to the Federal War and beyond, Venezuela endured decades of caudillo rule and civil conflict with minimal institutional development.",
    MAT: 5, CD: 4, CU: 2, MOR: 2,
    PRO: 1, COM: 1,
    ZS: 5, ONT_H: 2, ONT_S: 3,
    PF: 2, TRB: 4, ENG: 3,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.16, religious: 0.41, class: 0.05, ideological: 0.26, gender: 0.09, political_tribe: 0.25 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Venezuela",
    regime: "Gomez/Oil State",
    startYear: 1909,
    endYear: 1957,
    description:
      "Juan Vicente Gomez's long dictatorship coincided with massive oil discoveries that transformed Venezuela into a petro-state under military modernizers.",
    MAT: 5, CD: 4, CU: 2, MOR: 2,
    PRO: 2, COM: 1,
    ZS: 4, ONT_H: 2, ONT_S: 2,
    PF: 1, TRB: 4, ENG: 2,
    EPS: 1, AES: 4,
    morBoundaries: { boundaries: { national: 0.76, ethnic_racial: 0.16, religious: 0.41, class: 0.05, ideological: 0.26, gender: 0.09, political_tribe: 0 }, intensity: 2.25 },
  },
  {
    jurisdiction: "Venezuela",
    regime: "Punto Fijo Democracy",
    startYear: 1958,
    endYear: 1988,
    description:
      "The Punto Fijo pact between AD and COPEI delivered stable two-party democracy funded by oil wealth, becoming a model for Latin American governance.",
    MAT: 3, CD: 3, CU: 3, MOR: 3,
    PRO: 4, COM: 5,
    ZS: 2, ONT_H: 3, ONT_S: 2,
    PF: 5, TRB: 3, ENG: 4,
    EPS: 1, AES: 0,
    morBoundaries: { boundaries: { national: 0.17, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.24, gender: 0.07, political_tribe: 1 }, intensity: 3 },
  },
  {
    jurisdiction: "Venezuela",
    regime: "Crisis/Caracazo",
    startYear: 1989,
    endYear: 1998,
    description:
      "Neoliberal austerity triggered the deadly Caracazo riots and two failed coup attempts by Hugo Chavez, collapsing public trust in the old parties.",
    MAT: 4, CD: 3, CU: 3, MOR: 3,
    PRO: 3, COM: 3,
    ZS: 4, ONT_H: 2, ONT_S: 5,
    PF: 3, TRB: 3, ENG: 4,
    EPS: 1, AES: 3,
    morBoundaries: { boundaries: { national: 0.05, ethnic_racial: 0.05, religious: 0.05, class: 0.05, ideological: 0.1, gender: 0.07, political_tribe: 0.5 }, intensity: 1.5 },
  },
  {
    jurisdiction: "Venezuela",
    regime: "Chavez",
    startYear: 1999,
    endYear: 2012,
    description:
      "Hugo Chavez's Bolivarian Revolution redistributed oil wealth, rewrote the constitution, and polarized society between chavistas and the opposition.",
    MAT: 1, CD: 3, CU: 3, MOR: 3,
    PRO: 1, COM: 1,
    ZS: 4, ONT_H: 4, ONT_S: 5,
    PF: 5, TRB: 5, ENG: 5,
    EPS: 3, AES: 4,
    morBoundaries: { boundaries: { national: 0.29, ethnic_racial: 0.05, religious: 0.05, class: 0.72, ideological: 0.62, gender: 0.1, political_tribe: 1 }, intensity: 3 },
  },
  {
    jurisdiction: "Venezuela",
    regime: "Maduro",
    startYear: 2013,
    endYear: 2026,
    description:
      "Nicolas Maduro's regime presided over economic collapse, mass emigration, and authoritarian consolidation amid a devastating humanitarian crisis.",
    MAT: 1, CD: 4, CU: 4, MOR: 2,
    PRO: 1, COM: 1,
    ZS: 5, ONT_H: 2, ONT_S: 4,
    PF: 1, TRB: 5, ENG: 4,
    EPS: 5, AES: 4,
    morBoundaries: { boundaries: { national: 0.72, ethnic_racial: 0.05, religious: 0.34, class: 0.72, ideological: 0.34, gender: 0.1, political_tribe: 0 }, intensity: 3 },
  },
];
